### ISSUE TITLE
Huet's algorithm is incorrect

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#119]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on May 12, 2011 14:36:59_

in case there is a unification between first order terms both containing a variable, the algorithm fails. For example:

huet("y:i","g(z:i):i")
huet("x(f(y:i):i):i","f(x(g(z:i):i):i):i")
huet("x(f(y:i):i):i","f(x(z:i):i):i")

in all we get the following:

scala> normalizeSub(v.next.get)
java.lang.StackOverflowError
	at at.logic.language.lambda.types.To.<init>(types.scala:26)
	at at.logic.language.hol.Function$.gd4$1(hol.scala:212)
	at at.logic.language.hol.Function$.unapply(hol.scala:209)
	at at.logic.algorithms.unification.hol.ConfigurationNode.transformation4a(HuetAlgorithm.scala:58)
	at at.logic.algorithms.unification.hol.HuetAlgorithm$.myFun1(HuetAlgorithm.scala:268)
	at at.logic.algorithms.unification.hol.HuetAlgorithm$$anon$1$$anonfun$$init$$1.apply(HuetAlgorithm.scala:303)
	at at.logic.algorithms.unification.hol.HuetAlgorithm$$anon$1$$anonfun$$init$$1.apply(HuetAlgorithm.scala:303)
	at at.logic.utils.executionModels.ndStream.NDStream.next(ndStream.scala:39)
	at at.logic.utils.executionModels.ndStream.NDStream.next(ndStream.scala:41)
	at at.logic.utils.executionM...

_Original issue: http://code.google.com/p/gapt/issues/detail?id=119_

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on May 13, 2011 02:36:17_

The bug is captured and partially solved. Please comment it.

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on May 13, 2011 02:44:24_

the flex flex pairs are now not taken into account when computing the substitution. A solution for \<x,g(y)> should be either:
1) x -> g(y) (rule (3)
2a) x -> g(H), y -> H or
2b) x -> g(y), H -> y (both for rules 4a,3,4b,3)

and not as right now: x -> g(H)

also, please implement rule (3), it is an important rule, even if redundant by itself. You see above why.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on May 16, 2011 04:01:18_

Actual Behaviour:

huet("A:i", "B:i").next

gives

[...]

No unifier! 

No unifier! 

No unifier! 

No unifier! 
java.lang.StackOverflowError
        at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:58)
        at sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(UTF_8.java:392)
        at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:447)
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:544)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:252)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:106)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:190)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:111)
        at java.io.PrintStream.write(PrintStream.java:476)
        at java.io.PrintStream.print(PrintStream.java:619)
        at java.io.PrintStream.println(PrintStream.java:773)
        at scala.Console$.println(Console.scala:197)
        at scala.Predef$.println(Predef.scala:180)
        at at.logic.algorithms.unifica...

Intended Behaviour:

huet("A:i", "B:i").next

gives

None

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on May 17, 2011 15:44:06_

Tomer, 

compiling rule 3 gives this error. Any idea why? 

/neumann/cdunchev/gapt/source/algorithms/unification/src/main/scala:-1: info: compiling
[INFO] Compiling 6 source files to /neumann/cdunchev/gapt/source/algorithms/unification/target/classes at 1305671844067
[INFO] java.lang.reflect.InvocationTargetException
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:597)
[INFO] 	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO] 	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.Error: ch.epfl.lamp.fjbg.JCode$OffsetTooBigException: offset too big to fit in 16 bits: 176688
[INFO] 	at ch.epfl.lamp.fjbg.JFieldOrMethod.writeTo(JFieldOrMethod.java:114)
[INFO] 	at ch.epfl.lamp.fjbg.JClass.writeTo(JClass.java:315)
[INFO] 	at scala.tools.nsc.backend.jvm.GenJVM$BytecodeGenerator.emitClass(GenJVM.scala:141)
[INFO] 	at scala.tools.nsc.backend.jvm.GenJVM$BytecodeGenerator.genClass(GenJVM.scala:262)
[INFO] 	at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase.apply(GenJVM.scala:56)
[INFO] 	at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase$$anonfun$run$3.apply(GenJVM.scala:52)
[INFO] 	at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase$$anonfun$run$3.apply(GenJVM.scala:52)
[INFO] 	at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:89)
[INFO] 	at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:89)
[INFO] 	at scala.collection.Iterator$class.foreach(Iterator.scala:631)
[INFO] 	at scala.collection.mutable.HashTable$$anon$1.foreach(HashTable.scala:161)
[INFO] 	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:194)
[INFO] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
[INFO] 	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:89)
[INFO] 	at scala.tools.nsc.backend.jvm.GenJVM$JvmPhase.run(GenJVM.scala:52)
[INFO] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:741)
[INFO] 	at scala.tools.nsc.Global$Run.compile(Global.scala:822)
[INFO] 	at scala.tools.nsc.Main$.process(Main.scala:106)
[INFO] 	at scala.tools.nsc.Main$.main(Main.scala:120)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	... 6 more
[INFO] Caused by: ch.epfl.lamp.fjbg.JCode$OffsetTooBigException: offset too big to fit in 16 bits: 176688
[INFO] 	at ch.epfl.lamp.fjbg.JCode.checkOffset16(JCode.java:896)
[INFO] 	at ch.epfl.lamp.fjbg.JCode.patchAllOffset(JCode.java:975)
[INFO] 	at ch.epfl.lamp.fjbg.JCode.freeze(JCode.java:95)
[INFO] 	at ch.epfl.lamp.fjbg.JMethod.freeze(JMethod.java:81)
[INFO] 	at ch.epfl.lamp.fjbg.JFieldOrMethod.writeTo(JFieldOrMethod.java:111)
[INFO] 	... 25 more
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240(Exit value: 240)

**Comment by newca12** [comment]
_From [shaoli...@gmail.com](https://code.google.com/u/113190107447576027220/) on May 17, 2011 23:19:47_

did you try mvn clean install

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 18, 2011 09:08:40_

**Labels:** -Priority-Critical Priority-High

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 06:36:11_

Milestone Release 3.0 should contain all functionality for CERes Omega...

**Labels:** Milestone-Release3.0

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 19, 2011 23:27:13_

**Labels:** Component-TheoremProvers

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on August 20, 2011 03:16:23_

Don't wary. It is correct. I will commit the wast change soon.

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on August 22, 2011 04:25:41_

Issue 126 has been merged into this issue.

**Comment by newca12** [comment]
_From [bruno...@gmail.com](https://code.google.com/u/105016684496602932564/) on August 24, 2011 00:19:46_

**Status:** Started
