### ISSUE TITLE
Some parts in gapt are not thread safe

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#214]
_From [olivier....@edla.org](https://code.google.com/u/100852032415239746600/) on November 22, 2012 23:49:15_

As you know all tests are executed concurrently by default in specs2.
So normally thread safe issues are detected from time to time given unpredictable behavior.
For an undetermined reason this does not work with Scala 2.9 & Specs2. So nothing is detected.
Scala 2.10 & specs2 seem to fix this and show that some parts in gapt are not thread safe.
This will be a major issue for you and for someone using your API.

Parts detected so far are :
cutIntroduction when running DecompositionTest
shlk when running sFOparserTest
ceres when running ProjectionTermTest 
ceres when running ClauseSetsTest

The root cause seem to be the use of vars inside singletons objects which is of course very bad practice.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=214_

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on November 27, 2012 04:01:08_

Hi Olivier,

can you be more specific regarding these errors? I changed some things in cutIntroduction but I would like to make sure that it is what was causing the error before I commit it. Can you maybe send the error message or tell me how to reproduce it?

Thanks!
Giselle

**Comment by newca12** [comment]
_From [olivier....@edla.org](https://code.google.com/u/100852032415239746600/) on November 27, 2012 15:40:55_

I do not want to waste your time. Actually gapt cannot be thread safe because Parser combinator are not thread safe in Scala 2.9.2 : https://issues.scala-lang.org/browse/SI-4929 The ticket is not closed but this is fixed in Scala 2.10

I just want to warn you that there is actually hidden problem in gapt regarding thread safety and and sooner or later these problems will show up.
I need to dig it further and in particular why these problems are currently hidden.
Why you are not hit (at least during specs2 tests) by (at least) well known thread issues in Scala 2.9.2 is a mystery.
Some specs2 tests should failed but they failed only with Scala 2.10 for an undetermined reason. 

What I can say for now :

There is no thread issue with cutIntroduction. It was a mistake. There will be problems with cutIntroduction code and Scala 2.10 but this is another story.

sFOparserTest reveal thread issues when the tests are not executed sequentially
sFOparser should::parse correctly a FO SLK-proof(at.logic.algorithms.shlk.sFOparserTest)  Time elapsed: 0.46 sec  \<<< ERROR!
at.logic.calculi.lk.base.LKRuleCreationException: Not matching formula occurrences found for application of the rule with the given formula
	at at.logic.calculi.slk.sCutRule$.apply(slk.scala:778)

ProjectionTermTest reveal thread issues when the tests are not executed sequentially
org.specs2.execute.Error$ThrowableException: StackOverflowError: null
Caused by: java.lang.StackOverflowError
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:28)
	at at.logic.language.lambda.typedLambdaCalculus.Var.getFreeAndBoundVariables(typedLambdaCalculus.scala:84)
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:33)
	at at.logic.language.lambda.typedLambdaCalculus.App.getFreeAndBoundVariables(typedLambdaCalculus.scala:243)
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:33)
	at at.logic.language.lambda.typedLambdaCalculus.App.getFreeAndBoundVariables(typedLambdaCalculus.scala:243)
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:32)
	at at.logic.language.lambda.typedLambdaCalculus.App.getFreeAndBoundVariables(typedLambdaCalculus.scala:243)
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:33)
	at at.logic.language.lambda.typedLambdaCalculus.App.getFreeAndBoundVariables(typedLambdaCalculus.scala:243)
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:33)
	at at.logic.language.lambda.typedLambdaCalculus.App.getFreeAndBoundVariables(typedLambdaCalculus.scala:243)
	at at.logic.language.lambda.typedLambdaCalculus.LambdaExpression$class.getFreeAndBoundVariables(typedLambdaCalculus.scala:33)
	at at.logic.language.lambda.typedLambdaCalculus.App.getFreeAndBoundVariables(typedLambdaCalculus.scala:243)
	at at.logic.language.lambda.typedLambdaCalculus.Abs$.unapply(typedLambdaCalculus.scala:226)
	at at.logic.language.hol.AllVar$.unapply(hol.scala:395)
	at at.logic.language.hol.HOLExpression$class.toString(hol.scala:42)
	at at.logic.language.hol.HOLApp.toString(hol.scala:155)
	at at.logic.calculi.occurrences$FormulaOccurrence.toString(occurrences.scala:26)
	at at.logic.transformations.ceres.UnfoldProjectionTerm$.apply(ProjectionTerm.scala:786)
	at at.logic.transformations.ceres.UnfoldProjectionTerm$.apply(ProjectionTerm.scala:824) \<= a loop here causing the StackOverflowError

ClauseSetsTest reveal thread issues when the tests are not executed sequentially
java.lang.Exception: Could not find a formula to construct the cut-configuration!
	at at.logic.transformations.ceres.struct.cutOccConfigToCutConfig$.getFormulaForCC(Struct.scala:204)
	at at.logic.transformations.ceres.struct.cutOccConfigToCutConfig$$anonfun$apply$1.apply(Struct.scala:181)
	at at.logic.transformations.ceres.struct.cutOccConfigToCutConfig$$anonfun$apply$1.apply(Struct.scala:175)
	at at.logic.transformations.ceres.struct.cutOccConfigToCutConfig$.apply(Struct.scala:175)
	at at.logic.transformations.ceres.struct.StructCreators$.handleSchemaProofLink(Struct.scala:482)
	at at.logic.transformations.ceres.struct.StructCreators$.extract(Struct.scala:476)
	at at.logic.transformations.ceres.struct.StructCreators$.handleBinary(Struct.scala:513)
	at at.logic.transformations.ceres.struct.StructCreators$.extract(Struct.scala:473)
	at at.logic.transformations.ceres.struct.StructCreators$.handleUnary(Struct.scala:509)
	at at.logic.transformations.ceres.struct.StructCreators$.extract(Struct.scala:471)
	at at.logic.transformations.ceres.struct.StructCreators$.extract(Struct.scala:461)
	at at.logic.transformations.ceres.clauseSets.ClauseSetsTest$$anonfun$1$$anonfun$apply$2.apply(ClauseSetsTest.scala:54)
	at at.logic.transformations.ceres.clauseSets.ClauseSetsTest$$anonfun$1$$anonfun$apply$2.apply(ClauseSetsTest.scala:49)

**Comment by newca12** [comment]
_From [cdunc...@gmail.com](https://code.google.com/u/102976883554608245195/) on December 02, 2012 09:27:20_

Many thanks for the nice explanation of the warnings, Olivier. I had a look at all places where this happens, because all of them are written by me. I have to think how to avoid the use of "var". At some places such as sFOparser.scala the solution is in different architecture of the code. It is not emergent, but at some point I definitely have to do it.

Best regards.

**Comment by gebner** [comment]
This should be fixed with the removal of the schema code.
