### ISSUE TITLE
TPTPFOLExporter exception: NoSuchElementException

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#252]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on November 30, 2013 19:49:49_

I just added a new test checking the validity of Prover9 proofs (Prover9Test.scala:336), it fails with the output below. In line 277 above there is a commented test which appears to detect the same problem. It includes a FIXME: "commented out since tptp export of quantifiers is still failing. Try again after merging Giselle's changes."

The system should::load prover9 proof pi and verify the validity of the formula using prover9(at.logic.integration_tests.MiscTest)  Time elapsed: 1.682 sec  \<<< ERROR!
java.util.NoSuchElementException: key not found: T
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptp(TPTPFOLExporter.scala:95)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:89)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:86)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptpFormula(TPTPFOLExporter.scala:85)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.exportFormula(TPTPFOLExporter.scala:59)
	at at.logic.parsing.language.tptp.TPTPFOLExporter$.tptp_proof_problem(TPTPFOLExporter.scala:36)
	at at.logic.provers.prover9.Prover9$.writeProofProblem(Prover9.scala:45)
	at at.logic.provers.prover9.Prover9$.isValid(Prover9.scala:109)
	at at.logic.provers.prover9.Prover9$.isValid(Prover9.scala:101)
	at at.logic.provers.prover9.Prover9Prover.isValid(Prover9.scala:425)
	at at.logic.integration_tests.MiscTest$$anonfun$1$$anonfun$apply$15$$anonfun$apply$mcV$sp$1$$anonfun$apply$16.apply$mcZ$sp(MiscTest.scala:203)
	at at.logic.integration_tests.MiscTest$$anonfun$1$$anonfun$apply$15$$anonfun$apply$mcV$sp$1$$anonfun$apply$16.apply(MiscTest.scala:203)
	at at.logic.integration_tests.MiscTest$$anonfun$1$$anonfun$apply$15$$anonfun$apply$mcV$sp$1$$anonfun$apply$16.apply(MiscTest.scala:203)
	at at.logic.integration_tests.MiscTest$$anonfun$1$$anonfun$apply$15$$anonfun$apply$mcV$sp$1.apply(MiscTest.scala:203)
	at at.logic.integration_tests.MiscTest$$anonfun$1$$anonfun$apply$15$$anonfun$apply$mcV$sp$1.apply(MiscTest.scala:201)
	at at.logic.integration_tests.MiscTest$$anonfun$1$$anonfun$apply$15.apply$mcV$sp(MiscTest.scala:201)

_Original issue: http://code.google.com/p/gapt/issues/detail?id=252_

**Comment by newca12** [comment]
_From [b.mallin...@gmx.at](https://code.google.com/u/117611913960154270727/) on December 11, 2013 13:02:23_

According to Daniel, it is likely that bound variables are not treated appropriately, but the problem might disappear with the new lambda calculus.
In `#254`, a related issue occurs

**Comment by frehn** [comment]
Since these tests now seem to run fine, I have commented them in in c4fd96e6b1ef8bf3e132482c51b26cc63cfbb467 and am closing this issue.
