### ISSUE TITLE
"Number of eigenvariables different from number of terms in computation of canonical solution"

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#317]
This happens on quite a few proofs in the TSTP library.

```scala
import at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction

val p = loadProver9LKProof("testing/TSTP/prover9/GRP/GRP039-3/Prover9---1109a.UNS-Ref.s.out")
CutIntroduction.one_cut_many_quantifiers(p, true)
```

Error:
```
Exception in thread "Thread-0" java.lang.AssertionError: assertion failed: Number of eigenvariables different from number of terms in computation of canonical solution
	at scala.Predef$.assert(Predef.scala:165)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$computeCanonicalSolutions$1$$anonfun$6.apply(CutIntroduction.scala:608)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$computeCanonicalSolutions$1$$anonfun$6.apply(CutIntroduction.scala:606)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$computeCanonicalSolutions$1.apply(CutIntroduction.scala:606)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$computeCanonicalSolutions$1.apply(CutIntroduction.scala:603)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$.computeCanonicalSolutions(CutIntroduction.scala:603)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$liftedTree1$1$1$$anonfun$3.apply(CutIntroduction.scala:314)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$liftedTree1$1$1$$anonfun$3.apply(CutIntroduction.scala:306)
	at scala.collection.immutable.List.map(List.scala:277)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$liftedTree1$1$1.apply(CutIntroduction.scala:306)
	at at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction$$anonfun$liftedTree1$1$1.apply(CutIntroduction.scala:249)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.run(timeout.scala:29)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by frehn** [comment]
Confirming the bug, thanks!

Note to self: apparently, the MultiGrammar is generated wrongly (the "ss" list only contains the variable alpha_0, when in fact the first cut should have eigenvariables alpha_0, alpha_1 as witnessed by the fact that both variables occur in the "us" list).

**Comment by frehn** [comment]
@gisellemnr, @DarwinsBuddy: I think I might have found the source of this problem. In Grammar.scala, in the method findValidGrammars, the grammars that are created are always of the form
```scala
new Grammar(u, (ev::Nil, s)::Nil) 
```
Note that the list of eigenvariables always has length 1. This was changed in 6ce117cca from the following code in 8ed8ac6
```scala
new Grammar(u, s, eigenvariable)
```
In the current version, the value of pairs is for example
```scala
List((tuple1(α_0, α_1),List(tuple1(a, c), tuple1(c, a), tuple1(inverse(c), inverse(inverse(b))))))
```
which appears to indicate that the two eigenvariables α_0, α_1 should be given to the Grammar constructor.

Giselle, Christoph: The commit message indicates that one of you wrote that code - may I ask you to have a look at it?

**Comment by DarwinsBuddy** [comment]
I think, that I can't really help you out here.
Giselle took my code and edited it, among other thinngs, to fit our needs
for one_cut_many_quantifiers.

I have to pass this issue on to Giselle.
Sry. :(


2015-04-08 17:58 GMT+02:00 Daniel Weller <notifications@github.com>:

> @gisellemnr <https://github.com/gisellemnr>, @DarwinsBuddy
> <https://github.com/DarwinsBuddy>: I think I might have found the source
> of this problem. In Grammar.scala, in the method findValidGrammars, the
> grammars that are created are always of the form
>
> new Grammar(u, (ev::Nil, s)::Nil)
>
> Note that the list of eigenvariables always has length 1. This was changed
> in 6ce117c
> <https://github.com/gapt/gapt/commit/6ce117cca61c2a01075c5c2f3e848fda44caafc7>
> from the following code in 8ed8ac6
> <https://github.com/gapt/gapt/commit/8ed8ac66b052db3debbc78fa08847221ee467a79>
>
> new Grammar(u, s, eigenvariable)
>
> In the current version, the value of pairs is for example
>
> List((tuple1(α_0, α_1),List(tuple1(a, c), tuple1(c, a), tuple1(inverse(c), inverse(inverse(b))))))
>
> which appears to indicate that the two eigenvariables α_0, α_1 should be
> given to the Grammar constructor.
>
> Giselle, Christoph: The commit message indicates that one of you wrote
> that code - may I ask you to have a look at it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gapt/gapt/issues/317#issuecomment-90959146>.
>



-- 
Tel.: +43 676 643 00 55
EMail: christoph.spoerk@gmail.com

**Comment by frehn** [comment]
@DarwinsBuddy: Thanks for the info!

I have prepared a preliminary fix for this bug here: https://github.com/frehn/gapt/tree/issue317. The cutIntro code now produces a proof with cut for the example from the original issue report.

In the commit https://github.com/frehn/gapt/commit/9b2704571d188461cfa1e4b4268ffc9c0bbc1300, I added a fix for the "new Grammar" issue I describe above (Grammar.scala:209), but I think it is insufficient since the correct order of the variables is not guaranteed. @gisellemnr, if you could supply a code that computes the eigenvariables in the correct order, I would be grateful.

**Comment by frehn** [comment]
@gebner: In the original issue report, you mention that the problem occurs with a few proofs from TPTP. Could you supply a list of this proofs, or suggest a way to compile such a list? Thanks!

**Comment by gebner** [comment]
Here's another one: ```testing/TSTP/prover9/HEN/HEN005-1/Prover9---1109a.UNS-Ref.s.out```

And it works on the ```issue317``` branch. :+1: 

This should (over a long time) output all such proofs:
```scala
import java.io.File

import at.logic.gapt.cli.GAPScalaInteractiveShellLibrary.loadProver9LKProof
import at.logic.gapt.proofs.lk.algorithms.cutIntroduction.CutIntroduction

object recursiveListFiles {
  def apply( fn: String ): List[File] = apply( new File( fn ) )

  def apply( f: File ): List[File] =
    if ( f.isDirectory )
      f.listFiles.toList.flatMap( apply )
    else
      List( f )
}

def prover9Proofs = recursiveListFiles( "testing/TSTP/prover9" ).filter( _.getName.endsWith( ".out" ) )

prover9Proofs foreach { fn =>
  try {
    val p = loadProver9LKProof(fn.getAbsolutePath)
    CutIntroduction.one_cut_many_quantifiers(p, false)
  } catch {
    case e: AssertionError => println(fn)
    case _: Throwable => ()
  }
}
```

**Comment by frehn** [comment]
Great, thanks!

**Comment by shetzl** [comment]
FYI, this also happens on the lattice/poset-example we are looking at for the cutintro-paper. I am therefore putting a "high priortiy" label on this issue.

**Comment by gisellemnr** [comment]
I pushed Daniel's commits from the issue317 branch to master and put Gabriel's script to run in the server. We should see if more assertion errors are thrown soon.
Stefan, can you test if Daniel's fix works for the lattice example?

**Comment by shetzl** [comment]
For checking the lattice example I need the veriT-import to work properly. I'll check as soon as the bugs are fixed.

**Comment by shetzl** [comment]
With the latest fix I can sucessfully compute the canonical solution, so from this point of view the bug can be considered as closed.

However I hit an assertion in MinimizeSolution. I will file a bug report as soon as this is reproducible on a cleaner basis (currently I am using the poset-experiment branch in my fork).

**Comment by frehn** [comment]
Let me reiterate that while the code I put into the issue317 branch (i.e. Grammar.scala:209) should correctly identify the *number of variables*, it will in general use an incorrect *order of variables*.  Hence the canonical solution can be computed (note that the original failing assertion was referring to the number of variables), but I would not be surprised if the problem in MinimizeSolution that @shetzl  reports is exactly due to the order being wrong (since a wrong order induces unprovable extended herbrand sequents).

**Comment by gebner** [comment]
Subsumed by #460.
