### ISSUE TITLE
assertion failed in fixDerivation (map is not injective)

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#323]
@frehn: Do one of the following in the CLI:
loadProver9LKProof( "testing/TSTP/prover9/ALG/ALG025+1/Prover9---1109a.THM-Ref.s.out" )
loadProver9LKProof( "testing/TSTP/prover9/ALG/ALG028+1/Prover9---1109a.THM-Ref.s.out" )

This fails with:
java.lang.AssertionError: assertion failed
  at scala.Predef$.assert(Predef.scala:151)
  at at.logic.gapt.proofs.resolution.algorithms.fixDerivation$.deriveBySymmetry(fixDerivation.scala:116)
  at at.logic.gapt.proofs.resolution.algorithms.fixDerivation$.handleInitialClause(fixDerivation.scala:179)
  at at.logic.gapt.proofs.resolution.algorithms.fixDerivation$.rec(fixDerivation.scala:208)
 [...]

It should create an LKProof.

**Comment by frehn** [comment]
Thank you Stefan, confirmed! Looking into it.

**Comment by frehn** [comment]
Fixed in ac3d85f895835109c4e04f66ba5fcbe1081dec16; please confirm and close if applicable :-)

**Comment by shetzl** [comment]
confirming the fix, both proofs now load fine for me.
