### ISSUE TITLE
java.lang.InterruptedException when checking for veriT

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#344]
One of the most frequent causes of failure in the Prover9TestCase.veriT validity in the regression tests is a java.lang.InterruptedException when checking for whether veriT is installed. A typical stacktrace is the following (obtained from Prover9TestCase.verit validity.SET786+1 in extended testing 55).

java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
	at scala.sys.process.ProcessImpl$SimpleProcess.exitValue(ProcessImpl.scala:219)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:113)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:129)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
	at at.logic.gapt.provers.veriT.VeriTProver.liftedTree1$1(VeriTProver.scala:71)
	at at.logic.gapt.provers.veriT.VeriTProver.<init>(VeriTProver.scala:70)
	at at.logic.gapt.testing.Prover9TestCase$$anonfun$test$3.apply$mcZ$sp(regressionTests.scala:34)
	at at.logic.gapt.testing.RegressionTestCase$StepCondition$$anonfun$$bang$minus$minus$1.apply$mcV$sp(utils.scala:139)
	at at.logic.gapt.testing.RegressionTestCase$StepCondition$$anonfun$$bang$minus$minus$1.apply(utils.scala:139)
	at at.logic.gapt.testing.RegressionTestCase$StepCondition$$anonfun$$bang$minus$minus$1.apply(utils.scala:139)
	at at.logic.gapt.testing.RegressionTestCase$TestRun.at$logic$gapt$testing$RegressionTestCase$$runStep(utils.scala:61)
	at at.logic.gapt.testing.RegressionTestCase$StepCondition.$bang$minus$minus(utils.scala:139)
	at at.logic.gapt.testing.Prover9TestCase.test(regressionTests.scala:34)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply$mcV$sp(utils.scala:45)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply(utils.scala:45)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply(utils.scala:45)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.liftedTree1$1(timeout.scala:34)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.run(timeout.scala:34)

**Comment by gebner** [comment]
I hope this will be solved by 3b89cd3a4de388beb83f344eddc21e683dd51d79.

**Comment by shetzl** [comment]
This still occurs very frequently (see extended testing run 57) therefore I am reopening this issue.
