### ISSUE TITLE
induction branch: findMinimalGrammars fails requirement: acyclicity violated

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#347]
@gebner I have tried the grammar-finding code in the induction branch on the poset-example we are currently working on in our cut-introduction meetings (and which currently cannot be solved by the Delta-Table algorithm due to an incompleteness of this algorithm). This example leads to a failed requirement:

Executing the script
https://gist.github.com/shetzl/858915451a0210403cea
leads to:
java.lang.IllegalArgumentException: requirement failed: acyclicity violated in (α_1,f(b,α_2)): α_2 not in Set()
  at scala.Predef$.require(Predef.scala:219)
  at at.logic.gapt.grammars.TratGrammar$$anonfun$5$$anonfun$apply$9.apply(grammars.scala:82)
  at at.logic.gapt.grammars.TratGrammar$$anonfun$5$$anonfun$apply$9.apply(grammars.scala:81)
  at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
  at at.logic.gapt.grammars.TratGrammar$$anonfun$5.apply(grammars.scala:81)
  at at.logic.gapt.grammars.TratGrammar$$anonfun$5.apply(grammars.scala:77)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at at.logic.gapt.grammars.TratGrammar.<init>(grammars.scala:77)
  at at.logic.gapt.grammars.TratGrammar$.apply(grammars.scala:67)
  at at.logic.gapt.grammars.minimizeGrammar$.apply(grammarFinding.scala:197)
  at at.logic.gapt.grammars.findMinimalGrammar$.apply(grammarFinding.scala:207)
  ... 53 elided

**Comment by gebner** [comment]
I fixed the exception, but I'm afraid this example still takes too long for the MaxSAT algorithm.
