### ISSUE TITLE
alpha-equality causes problem in Gentzen-style cut-elimination

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#351]
Since run 58, the regression test Prover9TestCase.cut-elim (cut-intro).SET347+4 fails with the following stacktrace:

```
at.logic.gapt.proofs.lk.base.LKRuleCreationException: Not matching formula occurrences found in List(∀α_1.(subset(sum(empty_set),α_1)∨member(f1(sum(empty_set),α_1),sum(empty_set)))[43031]) for application of the rule with the given formula ∀B.(subset(sum(empty_set),B)∨member(f1(sum(empty_set),B),sum(empty_set)))
	at at.logic.gapt.proofs.lk.CutRule$.apply(propositionalRules.scala:508)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.reduceGradeQ(ReductiveCutElim.scala:213)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.reduceGrade(ReductiveCutElim.scala:206)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.reduceCut(ReductiveCutElim.scala:177)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:171)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:135)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:155)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:155)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:155)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:155)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:155)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:155)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:135)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:133)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.cutElim(ReductiveCutElim.scala:133)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.apply(ReductiveCutElim.scala:80)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.eliminateAllByUppermost(ReductiveCutElim.scala:113)
	at at.logic.gapt.proofs.lk.ReductiveCutElim$.apply(ReductiveCutElim.scala:100)
	at at.logic.gapt.testing.Prover9TestCase$$anonfun$test$8.apply(regressionTests.scala:46)
	at at.logic.gapt.testing.Prover9TestCase$$anonfun$test$8.apply(regressionTests.scala:46)
	at at.logic.gapt.testing.RegressionTestCase$TestRun.at$logic$gapt$testing$RegressionTestCase$$runStep(utils.scala:61)
	at at.logic.gapt.testing.RegressionTestCase$StepBlock.$minus$minus$qmark(utils.scala:127)
	at at.logic.gapt.testing.Prover9TestCase.test(regressionTests.scala:46)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply$mcV$sp(utils.scala:45)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply(utils.scala:45)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply(utils.scala:45)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.liftedTree1$1(timeout.scala:34)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.run(timeout.scala:34)
```

@gebner: git bisection shows that this has been introduced in revision 7a3b14fd4f09212254132d538de01d5a7ee55a6c.

**Comment by gebner** [comment]
The cut rule explicitly checks for syntactic equality instead of alpha-equality; if I change it to alpha-equality, the test runs without errors.

Do we want to allow cuts on alpha-equivalent formulas?  (For comparison, we can contract alpha-equivalent formulas.)

**Comment by gebner** [comment]
Part of the reason seems to be that the introduced cut-formula is alpha-equal to a partial instance of a formula in the end sequent (the first quantifier is instantiated with sum(empty_set), the second quantifier remains--modulo alpha-equality).
