### ISSUE TITLE
incompatibility between ReductiveCutElim and CleanStructuralRules

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#356]
Doing the following in the CLI
```scala
val fn = "testing/TSTP/prover9/SWV/SWV043+1/Prover9---1109a.THM-Ref.s.out"
val p = loadProver9LKProof( fn )
ReductiveCutElim( p )
```
results in
```
at.logic.gapt.proofs.lk.base.LKRuleCreationException: Sequent ¬(true⊃true) :-  cannot be reached from true,¬(true⊃true) :-  by weakenings.
  at at.logic.gapt.proofs.lk.WeakeningMacroRule$.apply(macroRules.scala:1282)
  at at.logic.gapt.proofs.lk.CleanStructuralRules$$anonfun$apply$1.apply(CleanStructuralRules.scala:33)
  at at.logic.gapt.proofs.lk.CleanStructuralRules$$anonfun$apply$1.apply(CleanStructuralRules.scala:33)
  at at.logic.gapt.proofs.lk.CleanStructuralRules$$anonfun$at$logic$gapt$proofs$lk$CleanStructuralRules$$cleanStructuralRules$3$$anonfun$apply$6$$anonfun$apply$8.apply(CleanStructuralRules.scala:60)
  at at.logic.gapt.proofs.lk.CleanStructuralRules$$anonfun$at$logic$gapt$proofs$lk$CleanStructuralRules$$cleanStructuralRules$3$$anonfun$apply$6$$anonfun$apply$8.apply(CleanStructuralRules.scala:60)
  at scala.util.control.TailCalls$TailRec.result(TailCalls.scala:77)
  at at.logic.gapt.proofs.lk.CleanStructuralRules$.apply(CleanStructuralRules.scala:34)
  at at.logic.gapt.proofs.lk.ReductiveCutElim$.apply(ReductiveCutElim.scala:83)
  at at.logic.gapt.proofs.lk.ReductiveCutElim$.eliminateAllByUppermost(ReductiveCutElim.scala:113)
  at at.logic.gapt.proofs.lk.ReductiveCutElim$.apply(ReductiveCutElim.scala:100)
  ... 30 elided
```

This also happens for a few other files. This is a regression that has been introduced in commit c98670afde87f8ac96100fc64f6bae373565077f. @loewenheim could you have a look at this?

**Comment by loewenheim** [comment]
Fixed in commit 688f57bae436c5d09ec31f95531611cd548dca7e
