### ISSUE TITLE
CERES does not support free variables in end-sequent

### ISSUE THREAD

**Issue by seimes** [gapt/gapt#357]
A call to foCERES yields the following exception:
```javascript
java.lang.IllegalArgumentException: requirement failed: Instance of projection with end-sequent (P(v0)∨Q(v1)),∀x.¬P(x) :- P(v0),Q(v1),∃z.Q(z) is not equal to  :- P(v0),Q(v1) x (P(a)∨Q(b)),∀x.¬P(x) :- ∃z.Q(z)
  at scala.Predef$.require(Predef.scala:219)
  at at.logic.gapt.proofs.ceres.CERES$$anonfun$findMatchingProjection$1.apply(CERES.scala:167)
  at at.logic.gapt.proofs.ceres.CERES$$anonfun$findMatchingProjection$1.apply(CERES.scala:159)
  at at.logic.gapt.proofs.ceres.CERESR2LK$$anonfun$apply$2.apply(CERES.scala:65)
  at at.logic.gapt.proofs.ceres.CERESR2LK$$anonfun$apply$2.apply(CERES.scala:65)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:79)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:167)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:113)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:167)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:167)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:113)
  at at.logic.gapt.proofs.resolution.RobinsonToLK$.apply(RobinsonToLK.scala:51)
  at at.logic.gapt.proofs.ceres.CERESR2LK.apply(CERES.scala:65)
  at at.logic.gapt.proofs.ceres.CERESR2LK.apply(CERES.scala:52)
  at at.logic.gapt.proofs.ceres.CERESR2LK.apply(CERES.scala:33)
  ... 30 elided
```

The exception should be reproducible with the following code:

```javascript
val a = FOLVar("a")
val b = FOLVar("b")
val u = FOLVar("u")
val pa = FOLAtom("P", a::Nil)
val qb = FOLAtom("Q", b::Nil)
val pu = FOLAtom("P", u::Nil)
val qu = FOLAtom("Q", u::Nil)
val pb = FOLAtom("P", b::Nil)
val qa = FOLAtom("Q", a::Nil)

val paorqa = Or(pa,qa)
val pborqb = Or(pb,qb)

val ey = parse.fol("Exists y Or P(y) Q(y)")

val paorqb = Or(pa,qb)
val puorqu = Or(pu,qu)

val npu = Neg(pu)

val eqz = parse.fol("Exists z Q(z)")
val anpx = parse.fol("Forall x Neg P(x)")



val ax1 = Axiom(pa::Nil,pa::Nil)
val ax2 = Axiom(qb::Nil,qb::Nil)
val ax3 = Axiom(pu::Nil,pu::Nil)
val ax4 = Axiom(qu::Nil,qu::Nil)

val p1 = OrRight1Rule(ax1,pa,qa)
val p2 = ExistsRightRule(p1,paorqa,ey,a)

val p3 = OrRight2Rule(ax2,pb,qb)
val p4 = ExistsRightRule(p3,pborqb,ey,b)

val p5 = OrLeftRule(p2,p4,pa,qb)
val p6 = ContractionRightRule(p5,ey)

val p7 = NegLeftRule(ax3,pu)
val p8 = WeakeningRightRule(p7,qu)

val p9 = WeakeningLeftRule(ax4,npu)

val p10 = OrLeftRule(p8,p9,pu,qu)
val p11 = ContractionRightRule(p10,qu)
val p12 = ContractionLeftRule(p11,npu)
val p13 = ExistsRightRule(p12,qu,eqz,u)
val p14 = ForallLeftRule(p13,npu,anpx,u)
val p15 = ExistsLeftRule(p14,puorqu,ey,u)

val p16 = CutRule(p6,p15,ey)

foCERES(p16)
```

**Comment by quicquid** [comment]
Thanks for the bug report - i narrowed down to a problem with free variables (a,b) in the end-sequent. Changing

    val a = FOLVar("a")
    val b = FOLVar("b")

to

    val a = FOLConst("a")
    val b = FOLConst("b")

works . I can't spend more time for investigation at the moment, but I'll add the information of what goes wrong for later:

The clause set is: 
1) :- P(a),Q(b)
2) P(u) :- 
3) Q(u) :- 

If a and b are variables, they can be substituted in the refutation. In this case, we have a <- u; b<- v, but this changes the end-sequent.

The straightforward fix is to ground the end-sequent, but i'd like to support end-sequents with free variables directly.

**Comment by seimes** [comment]
You are right regarding the example, both a and b should be constant symbols. Thanks for pointing that out.
