### ISSUE TITLE
ExistsRightRule can introduce universal quantifiers

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#363]
```scala
import at.logic.gapt.formats.prover9.Prover9TermParserLadrStyle._
import at.logic.gapt.proofs.lk._

val ax = Axiom(parseFormula("P(c)"))
val exr = ExistsRightRule(ax, parseFormula("P(c)"), parseFormula("(all x (P(x)))"), parseTerm("c"))
println(exr.root)
```
```
P(c)[10004] :- ∀x.P(x)[10003]
```
:worried:

**Comment by gebner** [comment]
Fixed in lkNew:
```
at.logic.gapt.proofs.lkNew.LKRuleCreationException: Cannot create ExistsRightRule: Proposed main formula ∀x.P(x) is not existentially quantified.
  at at.logic.gapt.proofs.lkNew.RuleConvenienceObject.LKRuleCreationException(lkNew.scala:1625)
  at at.logic.gapt.proofs.lkNew.ExistsRightRule$.apply(lkNew.scala:1137)
```
:smiley:
