### ISSUE TITLE
RobinsonToLK fails during substitution

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#390]
For example on [GRP658+1](http://compile:8080/job/gapt%20extended%20testing/lastCompletedBuild/testReport/Prover9TestCase/RobinsonToLK/GRP658_p_1/):
```
at.logic.gapt.proofs.lk.LKQuantifierException: Substituting the variable v10 with the term v0 in the formula ∀v10.∀v2.mult(mult(mult(rd(v10,mult(v10,v10)),v10),mult(v10,v10)),v2)=mult(mult(mult(rd(v10,mult(v10,v10)),v10),v10),mult(v10,v2)) gives ∀v2.mult(mult(mult(rd(v0,mult(v0,v0)),v0),mult(v0,v0)),v2)=mult(mult(mult(rd(v0,mult(v0,v0)),v0),v0),mult(v0,v2)) instead of ∀v2.mult(mult(mult(rd(v10,mult(v10,v10)),v10),mult(v0,v0)),v2)=mult(mult(mult(rd(v10,mult(v10,v10)),v10),v0),mult(v0,v2))
	at at.logic.gapt.proofs.lk.WeakRuleHelper.getTerms(quantificationRules.scala:494)
	at at.logic.gapt.proofs.lk.ForallLeftRule$.apply(quantificationRules.scala:77)
	at at.logic.gapt.proofs.lk.applySubstitution$.handleRule(substitution.scala:183)
	at at.logic.gapt.proofs.lk.applySubstitution$.apply(substitution.scala:233)
	at at.logic.gapt.proofs.lk.applySubstitution$.apply(substitution.scala:233)
	at at.logic.gapt.proofs.lk.applySubstitution$.apply(substitution.scala:236)
	at at.logic.gapt.proofs.lk.applySubstitution$.apply(substitution.scala:233)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:89)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:98)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:89)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:97)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:98)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:89)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.recConvert(RobinsonToLK.scala:91)
	at at.logic.gapt.proofs.resolution.RobinsonToLK$.apply(RobinsonToLK.scala:33)
	at at.logic.gapt.testing.Prover9TestCase$$anonfun$2.apply(regressionTests.scala:27)
	at at.logic.gapt.testing.Prover9TestCase$$anonfun$2.apply(regressionTests.scala:27)
	at at.logic.gapt.testing.RegressionTestCase$TestRun.at$logic$gapt$testing$RegressionTestCase$$runStep(utils.scala:62)
	at at.logic.gapt.testing.RegressionTestCase$StepBlock.$minus$minus$minus(utils.scala:118)
	at at.logic.gapt.testing.Prover9TestCase.test(regressionTests.scala:27)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply$mcV$sp(utils.scala:45)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply(utils.scala:45)
	at at.logic.gapt.testing.RegressionTestCase$$anonfun$run$1.apply(utils.scala:45)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.liftedTree1$1(timeout.scala:35)
	at at.logic.gapt.utils.executionModels.timeout.withTimeout$$anon$1.run(timeout.scala:35)
```

Probably related to variant symbols #383?

**Comment by gebner** [comment]
Fixed together with #383 .
