### ISSUE TITLE
Delta-table algorithm: grammar does not cover language.

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#392]
@shetzl @gisellemnr 
```scala
val p = Prover9Importer.expansionProofFromFile("./testing/TSTP/prover9/ALG/ALG245-1/Prover9---1109a.UNS-Ref.s.out")
CutIntroduction.compressToEHS(p, hasEquality=true, method=DeltaTableMethod(true), verbose=true)
```
produces the following exception now:
```
at.logic.gapt.proofs.lk.cutIntroduction.CutIntroNonCoveringGrammarException: Grammar does not cover the following term in the Herbrand set:
{∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(a,c),mult(b,d)),mult(mult(mult(a,b),mult(c,d)),mult(mult(a,c),mult(b,d))),mult(mult(a,b),mult(c,d)))

Axiom: (τ)
Non-terminal vectors:
  (τ)
  (α_4, α_5, α_3, α_2, α_1, α_0)
Productions:
  τ -> -{mult(mult(mult(a,b),mult(c,d)),mult(mult(a,c),mult(b,d)))=mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d)))}

  τ -> {∀A.mult(A,A)=A}(mult(mult(a,b),mult(c,d)))

  τ -> {∀A.mult(A,A)=A}(mult(mult(a,c),mult(b,d)))

  τ -> {∀A.mult(A,A)=A}(mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))))

  τ -> {∀A.∀B.∀C.mult(A,mult(B,C))=mult(mult(A,B),mult(A,C))}(mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))),mult(mult(a,b),mult(c,d)),mult(mult(a,b),mult(c,d)))

  τ -> {∀A.∀B.∀C.mult(A,mult(B,C))=mult(mult(A,B),mult(A,C))}(mult(mult(α_0,α_1),mult(α_2,α_3)),mult(mult(a,α_4),mult(α_5,d)),mult(mult(α_0,α_1),mult(α_2,α_3)))

  τ -> {∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(a,b),mult(c,d)),mult(mult(a,c),mult(b,d)),mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))))

  τ -> {∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d)),mult(mult(a,b),mult(c,d)))

  τ -> {∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(a,c),mult(b,d)),mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))),mult(mult(a,c),mult(b,d)))

  τ -> {∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))),mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d)))

  τ -> {∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))),mult(mult(a,b),mult(c,d))),mult(mult(a,c),mult(b,d)),mult(mult(mult(a,c),mult(b,d)),mult(mult(a,b),mult(c,d))))

  τ -> {∀A.∀B.∀C.mult(mult(A,B),C)=mult(mult(A,C),mult(B,C))}(mult(mult(α_0,α_1),mult(α_2,α_3)),mult(mult(mult(a,α_4),mult(α_5,d)),mult(mult(α_0,α_1),mult(α_2,α_3))),mult(mult(a,b),mult(c,d)))

  τ -> {∀A.∀B.∀C.∀D.mult(mult(mult(A,B),mult(C,D)),mult(mult(mult(A,B),mult(C,D)),mult(mult(A,C),mult(B,D))))=mult(mult(A,C),mult(B,D))}(a,c,b,d)

  τ -> {∀A.∀B.∀C.∀D.mult(mult(mult(mult(A,B),mult(C,D)),mult(mult(A,C),mult(B,D))),mult(mult(A,C),mult(B,D)))=mult(mult(A,B),mult(C,D))}(a,c,b,d)

  α_4 -> a
  α_5 -> b
  α_3 -> c
  α_2 -> d
  α_1 -> c
  α_0 -> b

  α_4 -> a
  α_5 -> c
  α_3 -> b
  α_2 -> d
  α_1 -> b
  α_0 -> c

  α_4 -> mult(a,c)
  α_5 -> mult(b,d)
  α_3 -> mult(a,b)
  α_2 -> mult(c,d)
  α_1 -> b
  α_0 -> c


	at at.logic.gapt.proofs.lk.cutIntroduction.CutIntroduction$$anonfun$compressToEHS$10$$anonfun$apply$13.apply(CutIntroduction.scala:206)
	at at.logic.gapt.proofs.lk.cutIntroduction.CutIntroduction$$anonfun$compressToEHS$10$$anonfun$apply$13.apply(CutIntroduction.scala:204)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	
```

**Comment by gebner** [comment]
Probably related to #360 and #317.

**Comment by gebner** [comment]
Subsumed by issue #460.
