### ISSUE TITLE
cleanStructuralRules: eigenvariable condition is violated

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#417]
```scala
CutIntroduction.compressLKProof(
  Prover9Importer.lkProofFromFile(
    "./testing/TSTP/prover9/ALG/ALG073+1/Prover9---1109a.THM-Ref.s.out"),
  method = DeltaTableMethod(manyQuantifiers=true),
  verbose = true)
```
```
...
at.logic.gapt.proofs.lkNew.LKRuleCreationException: Cannot create ForallRightRule: Eigenvariable condition is violated.
  at at.logic.gapt.proofs.lkNew.LKProof.LKRuleCreationException(lkNew.scala:12)
  at at.logic.gapt.proofs.lkNew.ForallRightRule.<init>(lkNew.scala:997)
  at at.logic.gapt.proofs.lkNew.ForallRightRule$.apply(lkNew.scala:1017)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:339)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:43)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:311)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:311)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:311)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:311)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:311)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:311)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply_(cleanStructuralRules.scala:24)
  at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply(cleanStructuralRules.scala:7)
  at at.logic.gapt.cutintro.CutIntroduction$$anonfun$12.apply(CutIntroduction.scala:275)
  at at.logic.gapt.cutintro.CutIntroduction$$anonfun$12.apply(CutIntroduction.scala:275)
  at at.logic.gapt.utils.logging.IgnoreMetrics.time(metrics.scala:41)
  at at.logic.gapt.utils.logging.metrics$.time(metrics.scala:48)
  at at.logic.gapt.cutintro.CutIntroduction$.constructLKProof(CutIntroduction.scala:274)
  at at.logic.gapt.cutintro.CutIntroduction$$anonfun$compressToLK$1.apply(CutIntroduction.scala:291)
  at at.logic.gapt.cutintro.CutIntroduction$$anonfun$compressToLK$1.apply(CutIntroduction.scala:291)
  at scala.Option.map(Option.scala:146)
  at at.logic.gapt.cutintro.CutIntroduction$.compressToLK(CutIntroduction.scala:291)
  at at.logic.gapt.cutintro.CutIntroduction$.compressLKProof(CutIntroduction.scala:302)
  ... 43 elided
```

**Comment by loewenheim** [comment]
Yesterday on my work machine, I could reproduce this, but today at home, I can't. Does it still happen at your end?

**Comment by gebner** [comment]
Hah, I apparently fixed this earlier today:
```
1d634b247405a37be675c0cb4fd1644ffc27b805 is the first bad commit
commit 1d634b247405a37be675c0cb4fd1644ffc27b805
Author: Gabriel Ebner <gebner@gebner.org>
Date:   Thu Oct 22 09:16:46 2015 +0200

    Refactor types to have a single base type class.

:040000 040000 d5a107eddb1a92fc2b2751df725db15e3bdcd87f 0bacdc3c201bc82f8fb2069cf5c23b282ee20f4d M      src
bisect run success
```
("bad commit" means bug-free commit here)

Unfortunately I haven't got the faintest idea on why this fixed it.  I hope I didn't break the eigenvariable condition check, but there *are* unit tests for that...

**Comment by gebner** [comment]
Found another one:
```scala
  CutIntroduction.compressLKProof(
    Prover9Importer.lkProofFromFile(
      glob( "testing/TSTP/prover9/**/ALG203+1/*.s.out" ).head
    ),
    method = DeltaTableMethod( manyQuantifiers = true ),
    verbose = true
  )
```
prints
```
Exception in thread "main" at.logic.gapt.proofs.lkNew.LKRuleCreationException: Cannot create ForallRightRule: Eigenvariable condition is violated: ∀v0.(¬sorti1(v0)∨sorti2(h(v0))), ∀v00.∀v1.((¬sorti1(v00)∨¬sorti1(v1))∨h(op1(v00,v1))=op2(h(v00),h(v1))) :- ¬sorti1(α_0), ¬sorti1(α_0) contains α_0
	at at.logic.gapt.proofs.lkNew.LKProof.LKRuleCreationException(lkNew.scala:12)
	at at.logic.gapt.proofs.lkNew.ForallRightRule.<init>(lkNew.scala:1067)
	at at.logic.gapt.proofs.lkNew.ForallRightRule$.apply(lkNew.scala:1101)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:318)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:43)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:290)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:290)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:290)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:290)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:290)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.at$logic$gapt$proofs$lkNew$cleanStructuralRules$$apply_(cleanStructuralRules.scala:24)
	at at.logic.gapt.proofs.lkNew.cleanStructuralRules$.apply(cleanStructuralRules.scala:7)
	at at.logic.gapt.cutintro.CutIntroduction$$anonfun$14.apply(CutIntroduction.scala:308)
	at at.logic.gapt.cutintro.CutIntroduction$$anonfun$14.apply(CutIntroduction.scala:308)
	at at.logic.gapt.utils.logging.IgnoreMetrics.time(metrics.scala:41)
	at at.logic.gapt.utils.logging.metrics$.time(metrics.scala:48)
	at at.logic.gapt.cutintro.CutIntroduction$.constructLKProof(CutIntroduction.scala:307)
	at at.logic.gapt.cutintro.CutIntroduction$$anonfun$compressToLK$1.apply(CutIntroduction.scala:324)
	at at.logic.gapt.cutintro.CutIntroduction$$anonfun$compressToLK$1.apply(CutIntroduction.scala:324)
	at scala.Option.map(Option.scala:146)
	at at.logic.gapt.cutintro.CutIntroduction$.compressToLK(CutIntroduction.scala:324)
	at at.logic.gapt.cutintro.CutIntroduction$.compressLKProof(CutIntroduction.scala:335)
```

**Comment by gebner** [comment]
It seems that I once again "fixed" the bug with the latest changes in cut-intro. :frowning:

**Comment by loewenheim** [comment]
Heh, I was wondering already whether it was my reworked cleanStructuralRules that did it ;)

**Comment by gebner** [comment]
Seems to be fixed with the new cleanStructuralRules, this error does no longer appear in the regression tests.

**Comment by loewenheim** [comment]
Glad to hear it. To be honest I'm rather proud of the new CSR :P
