### ISSUE TITLE
ExtractInterpolant: Cannot create ContractionLeftRule

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#429]
@seimes 
```scala
val sequent = toDeep(Prover9Importer.expansionProofFromFile(glob("**/prover9/**/GEO051-3/*.s.out").head))
println(ExtractInterpolant(sequent.antecedent ++: Sequent(), Sequent() :++ sequent.succedent, Prover9))
```
prints
```
at.logic.gapt.proofs.lkNew.LKRuleCreationException: Cannot create ContractionLeftRule: Formula ((¬between(u,v,w)∨(¬between(u,w,x)∨between(v,w,x)))∧(¬between(u,v,x)∨(¬between(u,x,w)∨between(v,x,w)))) only found 1 times in antecedent of between(u,v,w), between(u,v,x), (¬between(u,v,x)∨(¬between(u,v,w)∨(u=v∨(between(u,x,w)∨between(u,w,x))))), between(u,v,w), ((¬between(u,v,w)∨(¬between(u,w,x)∨between(v,w,x)))∧(¬between(u,v,x)∨(¬between(u,x,w)∨between(v,x,w)))) :- between(u,x,w), (((⊥∨(⊥∨((⊥∨(⊥∨(⊥∨(⊥∨⊥))))∨⊥)))∨((⊥∨(v=u∧⊤))∧⊤))∨((⊥∨(⊥∨(⊥∨between(v,w,x))))∧⊤)).
	at at.logic.gapt.proofs.lkNew.ConvenienceConstructor.LKRuleCreationException(lkNew.scala:1828)
	at at.logic.gapt.proofs.lkNew.ConvenienceConstructor$$anonfun$validateIndices$4.apply(lkNew.scala:1917)
	at at.logic.gapt.proofs.lkNew.ConvenienceConstructor$$anonfun$validateIndices$4.apply(lkNew.scala:1913)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at at.logic.gapt.proofs.lkNew.ConvenienceConstructor.validateIndices(lkNew.scala:1913)
	at at.logic.gapt.proofs.lkNew.ConvenienceConstructor.findAndValidate(lkNew.scala:1944)
	at at.logic.gapt.proofs.lkNew.ContractionLeftRule$.apply(lkNew.scala:334)
	at at.logic.gapt.proofs.lkNew.Interpolate$.apply(applyInterpolation.scala:167)
	at at.logic.gapt.proofs.lkNew.Interpolate$.applyUpCutLeft(applyInterpolation.scala:424)
	at at.logic.gapt.proofs.lkNew.Interpolate$.apply(applyInterpolation.scala:182)
	at at.logic.gapt.proofs.lkNew.Interpolate$.applyUpUnary(applyInterpolation.scala:393)
	at at.logic.gapt.proofs.lkNew.Interpolate$.apply(applyInterpolation.scala:164)
	at at.logic.gapt.proofs.lkNew.Interpolate$.applyUpUnary(applyInterpolation.scala:393)
	at at.logic.gapt.proofs.lkNew.Interpolate$.apply(applyInterpolation.scala:164)
	at at.logic.gapt.proofs.lkNew.Interpolate$.applyUpCutLeft(applyInterpolation.scala:424)
	at at.logic.gapt.proofs.lkNew.Interpolate$.apply(applyInterpolation.scala:182)
	at at.logic.gapt.proofs.lkNew.ExtractInterpolant$.apply(applyInterpolation.scala:12)
	at at.logic.gapt.proofs.lkNew.ExtractInterpolant$.apply(applyInterpolation.scala:27)
```

**Comment by loewenheim** [comment]
Fixed in https://github.com/gapt/gapt/commit/ca55bfc2efb65114a333a7a7c89252236aa0104c.
