### ISSUE TITLE
solvePropositional: does not find proofs that require weakening

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#430]
For example
```scala
val p = FOLAtom("p")
solve.solvePropositional((p & p) +: Sequent() :+ p)
```
prints
```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at at.logic.gapt.proofs.lkNew.solve$.prove(solve.scala:72)
	at at.logic.gapt.proofs.lkNew.solve$.applyActionAntecedent(solve.scala:181)
	at at.logic.gapt.proofs.lkNew.solve$.prove(solve.scala:99)
	at at.logic.gapt.proofs.lkNew.solve$.startProving(solve.scala:58)
	at at.logic.gapt.proofs.lkNew.solve$.solvePropositional(solve.scala:34)
```

**Comment by loewenheim** [comment]
I looked into this and it appears that currently the algorithm can only treat sequents that don't contain duplicate formulas. Simply commenting out the relevant assertion didn't work, so I'm afraid that this will necessitate a larger-scale rewrite.

**Comment by shetzl** [comment]
Not dealing with sequents that contain duplicate formulas is not a bug, it's a feature ;-) see the comment on 8174f8f.
