### ISSUE TITLE
minimalExpansionSequent returns non-tautological expansion sequents

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#441]
This happened when playing with the poset example, so sorry for the long example, I haven't been able to find a smaller one:
```scala
val f = FOLFunctionHead("f", 2)
val Seq(u, v, w, x, y, z) = Seq("u", "v", "w", "x", "y", "z") map { FOLVar(_) }
val Seq(a, b, c) = Seq("a", "b", "c") map { FOLConst(_) }

val C = All(x, All(y, f(x, y) === f(y, x)))
val AS = All(u, All(v, (f(u, v) === u) --> ((f(v, u) === v) --> (u === v))))

val A = All(x, All(y, All(z, f(f(x, y), z) === f(x, f(y, z)))))
val Tpo = All(x, All(y, All(z, (f(x, y) === x) --> ((f(y, z) === y) --> (f(x, z) === x)))))

val trans = (ProofBuilder
  c VeriT.getLKProof(instantiate(A, Seq(u, v, w)) +: Sequent() :+ instantiate(Tpo, Seq(u, v, w))).get
  u (ForallLeftBlock(_, A, Seq(u, v, w)))
  u (ForallRightBlock(_, Tpo, Seq(u, v, w)))
  qed)

val antisymm = (ProofBuilder
  c VeriT.getLKProof(instantiate(C, Seq(u, v)) +: Sequent() :+ instantiate(AS, Seq(u, v))).get
  u (ForallLeftBlock(_, C, Seq(u, v)))
  u (ForallRightBlock(_, AS, Seq(u, v)))
  qed)

val lhs = ContractionMacroRule(AndRightRule(antisymm, AS, trans, Tpo))

val rhs = {
  val EAS = formulaToExpansionTree(AS, List(Substitution(u -> a, v -> b), Substitution(u -> b, v -> c)), false)

  val ETpo = formulaToExpansionTree(Tpo, List(Substitution(x -> b, y -> c, z -> a), Substitution(x -> c, y -> a, z -> b)), false)

  val ETcut = ETAnd(EAS, ETpo)
  val conc = ((f(a, b) === a) & (f(b, c) === b) & (f(c, a) === c)) --> ((a === b) & (b === c))
  val Econc = formulaToExpansionTree(conc, true)

  ExpansionProofToLK(ETcut +: Sequent() :+ Econc)
}

// proof with cut
val pwc = CutRule(lhs, rhs, And(AS, Tpo))

val p = ReductiveCutElimination(pwc)

val E = LKToExpansionProof(p)
require(Sat4j isValid toDeep(E))
println("expansion sequent ok, now trying the minimized one:")
val Some(minE) = minimalExpansionSequent(E, Sat4j)
println("counter-model:")
println(Sat4j solve toDeep(minE).toNegFormula)
require(Sat4j isValid toDeep(minE))
```

Here `E` is an expansion sequent with explicit instances of equality axioms, and is tautological (Sat4j says so).  However minimizing it with `minimalExpansionSequent` returns a non-tautological expansion sequent (it is however quasi-tautological, for what it's worth):

```
expansion sequent ok, now trying the minimized one:
counter-model:
Some(a=a -> true
a=b -> false
b=a -> false
b=b -> true
b=c -> true
b=f(a,b) -> false
b=f(b,a) -> false
c=b -> false
c=c -> true
c=f(b,c) -> false
c=f(c,b) -> false
f(a,b)=a -> true
f(a,b)=f(b,a) -> true
f(b,a)=b -> false
f(b,a)=f(a,b) -> true
f(b,a)=f(b,f(c,a)) -> true
f(b,a)=f(f(b,c),a) -> true
f(b,c)=b -> true
f(b,c)=f(c,b) -> true
f(b,f(c,a))=f(b,c) -> true
f(c,a)=c -> true
f(c,b)=c -> false
f(c,b)=f(b,c) -> true
f(c,b)=f(c,f(a,b)) -> true
f(c,b)=f(f(c,a),b) -> true
f(c,f(a,b))=f(c,a) -> true
f(f(b,c),a)=f(b,a) -> true
f(f(b,c),a)=f(b,f(c,a)) -> true
f(f(c,a),b)=f(c,b) -> true
f(f(c,a),b)=f(c,f(a,b)) -> true
...)
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:207)
	at Main$$anon$1.<init>(poset-example.scala:64)
	at Main$.main(poset-example.scala:1)
```

**Comment by loewenheim** [comment]
If you try the same thing with minimalExpansionSequents, i.e. the algorithm that computes all of them, it tells you that the original sequent is already minimal.

**Comment by loewenheim** [comment]
The problem seems to be related to `compressQuantifiers` or `decompressQuantifiers`: If you compress and then decompress, you don't get the original sequent.
