### ISSUE TITLE
solvePropositional: cannot create AndLeftMacroRule

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#442]
In the [latest regression tests](http://compile.logic.tuwien.ac.at/job/gapt%20extended%20testing/83/testReport/Prover9TestCase/solvePropositional/SWV763_m_1/), solvePropositional fails to prove the deep formula of the expansion sequent extracted from SWV763-1:

```scala
solve.solvePropositional(toDeep(Prover9Importer.expansionProofFromFile(glob("**/SWV763-1/Prover9-*.s.out").head)))
```
prints
```
at.logic.gapt.proofs.lkNew.LKRuleCreationException: Cannot create AndLeftMacroRule: Neither Right((hBOOL(c_in(v_evs2,c_NS__Shared__Mirabelle_Ons__shared,tc_List_Olist(tc_Event_Oevent)))∨¬hBOOL(hAPP(c_NS__Shared__Mirabelle_Ons__shared,v_evs2)))) nor Right((hBOOL(c_in(v_KAB,c_Message_OsymKeys,tc_nat))∨¬hBOOL(hAPP(c_Message_OsymKeys,v_KAB)))) has been found in antecedent of (hBOOL(hAPP(c_Message_OsymKeys,v_KAB))∨¬hBOOL(c_in(v_KAB,c_Message_OsymKeys,tc_nat))), (¬hBOOL(c_in(v_KAB,c_Message_OkeysFor(c_Message_Oparts(c_Event_Oknows(c_Message_Oagent_OSpy,v_evs2))),tc_nat))∨(¬hBOOL(c_in(v_evs2,c_NS__Shared__Mirabelle_Ons__shared,tc_List_Olist(tc_Event_Oevent)))∨(¬hBOOL(c_in(v_KAB,c_Message_OsymKeys,tc_nat))∨hBOOL(c_in(hAPP(c_Message_Omsg_OKey,v_KAB),c_Event_Oused(v_evs2),tc_Message_Omsg))))), hBOOL(c_in(v_KAB,c_Message_OsymKeys,tc_nat)), hBOOL(c_in(v_evs2,c_NS__Shared__Mirabelle_Ons__shared,tc_List_Olist(tc_Event_Oevent))), hBOOL(c_in(c_Message_Omsg_OCrypt(v_KAB,c_Message_Omsg_ONonce(v_NB)),c_Message_Oparts(c_Event_Oknows(c_Message_Oagent_OSpy,v_evs2)),tc_Message_Omsg)), (hBOOL(c_in(v_KAB,c_Message_OkeysFor(c_Message_Oparts(c_Event_Oknows(c_Message_Oagent_OSpy,v_evs2))),tc_nat))∨(¬hBOOL(c_in(v_KAB,c_Message_OsymKeys,tc_nat))∨¬hBOOL(c_in(c_Message_Omsg_OCrypt(v_KAB,c_Message_Omsg_ONonce(v_NB)),c_Message_Oparts(c_Event_Oknows(c_Message_Oagent_OSpy,v_evs2)),tc_Message_Omsg)))), (hBOOL(hAPP(c_NS__Shared__Mirabelle_Ons__shared,v_evs2))∨¬hBOOL(c_in(v_evs2,c_NS__Shared__Mirabelle_Ons__shared,tc_List_Olist(tc_Event_Oevent)))) :- hBOOL(c_in(hAPP(c_Message_Omsg_OKey,v_KAB),c_Event_Oused(v_evs2),tc_Message_Omsg)).
  at at.logic.gapt.proofs.lkNew.ConvenienceConstructor.LKRuleCreationException(lkNew.scala:1828)
  at at.logic.gapt.proofs.lkNew.AndLeftMacroRule$.withOccConnector(macroRules.scala:42)
  at at.logic.gapt.proofs.lkNew.AndLeftMacroRule$.apply(macroRules.scala:23)
  at at.logic.gapt.proofs.lkNew.solve$$anonfun$5.apply(solve.scala:181)
  at at.logic.gapt.proofs.lkNew.solve$$anonfun$5.apply(solve.scala:180)
  at scala.Option.map(Option.scala:146)
  at at.logic.gapt.proofs.lkNew.solve$.applyActionAntecedent(solve.scala:180)
  at at.logic.gapt.proofs.lkNew.solve$.prove(solve.scala:99)
  at at.logic.gapt.proofs.lkNew.solve$.applyActionAntecedent(solve.scala:180)
  at at.logic.gapt.proofs.lkNew.solve$.prove(solve.scala:99)
  at at.logic.gapt.proofs.lkNew.solve$.startProving(solve.scala:58)
  at at.logic.gapt.proofs.lkNew.solve$.solvePropositional(solve.scala:34)
  ... 43 elided
```

**Comment by gebner** [comment]
This is now starting to happen in lots of cut-intro tests as well: e.g. [GRP123-1.003](http://compile.logic.tuwien.ac.at/job/gapt%20extended%20testing/84/testReport/Prover9TestCase/cut-introduction/GRP123_m_1_003/)

**Comment by gebner** [comment]
And it also happens in `ExpansionProofToLK` which is maybe easier to reproduce:
```scala
ExpansionProofToLK(Prover9Importer expansionProofFromFile glob("**/AGT005+1/Prover9*.s.out").head)
```

**Comment by gebner** [comment]
And it happens in `solvePropositional` as well:
```scala
solve solvePropositional toDeep(Prover9Importer expansionProofFromFile glob("**/GEO177+1/Prover9*.s.out").head)
```
