### ISSUE TITLE
Prover9.getLKProof throws an Exception in ExpansionProofToLK

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#482]
Please consider the following cli commands:

    val sigstr = "var x,y,s : i; const f : i>i; const < : i>i>o;"
    val f = parseLLKFormula(sigstr+"(all x exists y (x<y & f(y) = s)) <-> -(exists x all y (-x<y | f(y) != s))")
     Prover9.isValid(f)
     Prover9.getLKProof(f)

As expected, isValid returns true, but the last fails with:

    java.util.NoSuchElementException: None.get
      at scala.None$.get(Option.scala:347)
      at scala.None$.get(Option.scala:345)
      at at.logic.gapt.proofs.expansion.ExpansionProofToLK$.apply(expansionProofs.scala:237)
      at at.logic.gapt.proofs.resolution.RobinsonToLK$$anonfun$1.apply(RobinsonToLK.scala:35)
      at at.logic.gapt.proofs.resolution.RobinsonToLK$$anonfun$1.apply(RobinsonToLK.scala:33)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
      at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
      at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
      at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
      at scala.collection.AbstractTraversable.map(Traversable.scala:104)
      at at.logic.gapt.proofs.resolution.RobinsonToLK$.apply(RobinsonToLK.scala:33)
      at at.logic.gapt.provers.ResolutionProver$$anonfun$getLKProof$1$$anonfun$apply$3.apply(ResolutionProver.scala:48)
      at at.logic.gapt.provers.ResolutionProver$$anonfun$getLKProof$1$$anonfun$apply$3.apply(ResolutionProver.scala:47)
      at scala.Option.map(Option.scala:146)
      at at.logic.gapt.provers.ResolutionProver$$anonfun$getLKProof$1.apply(ResolutionProver.scala:47)
      at at.logic.gapt.provers.ResolutionProver$$anonfun$getLKProof$1.apply(ResolutionProver.scala:45)
      at at.logic.gapt.provers.ResolutionProver.withGroundVariables(ResolutionProver.scala:22)
      at at.logic.gapt.provers.ResolutionProver.getLKProof(ResolutionProver.scala:45)

**Comment by gebner** [comment]
Yup, that sequent contains strong quantifiers, and deskolemization is not implemented yet.

Do you need the LK proof for anything in particular?  I'll add a better error message.

**Comment by quicquid** [comment]
Ah I see - i don't need the proof, I was just using gapt to double-check something i did by hand and was surprised it didn't work. By the way, I'd also be happy about a proof of the skolemized end-sequent. Is the way to go to skolemize by calling the appropriate functions or do we provide some interface?

**Comment by gebner** [comment]
You can get a Skolemized expansion proof by running `getExpansionProof`, but for `getLKProof` you need to call `skolemize` yourself.

IMHO `getLKProof` should only return proofs of the provided end-sequent.

**Comment by gebner** [comment]
Yup, `getExpansionProof` works on your example:
```
scala> Prover9 getExpansionProof (Sequent() :+ hof"(all x exists y (x<y & f(y) = s)) <-> -(exists x all y (-x<y | f(y) != s))")
res1: Option[at.logic.gapt.proofs.expansion.ExpansionProof] =
Some(ExpansionProofWithCut(List(),
:-
[p29] ETAnd(p14, p28)
[p28] ETImp(p22, p27)
[p27] ETSkolemQuantifier(∀x ∃y (x < y ∧ f(y) = s), 's_{6}', p26)
[p26] ETWeakQuantifier(∃y ('s_{6}' < y ∧ f(y) = s), 's_{4}'('s_{6}'), p25)
[p25] ETAnd(p23, p24)
[p24] ETAtom(f('s_{4}'('s_{6}')) = s, true)
[p23] ETAtom('s_{6}' < 's_{4}'('s_{6}'), true)
[p22] ETNeg(p21)
[p21] ETWeakQuantifier(∃x ∀y (¬x < y ∨ ¬f(y) = s), 's_{6}', p20)
[p20] ETSkolemQuantifier(∀y (¬'s_{6}' < y ∨ ¬f(y) = s), 's_{4}'('s_{6}'), p19)
[p19] ETOr(p16, p18)
[p18] ETNeg(p17)
[p17] ETAtom(f('s_{4}'('s_{6}')) = s, false)
[p16] ETNeg(p15)
[p15] ETAtom('s_{6}' < 's_{4}'('s_{6}'), false)
[p14] ETImp(p5, p13)
[p13] ETNeg(p12)
[p12] ETSkolemQuantifier(∃x ∀y (¬x < y ∨ ¬f(y) = s), ...

scala> res1.get.deep
res4: at.logic.gapt.proofs.Sequent[at.logic.gapt.expr.HOLFormula] =

:-
('s_{2}' < 's_{0}'('s_{2}') ∧ f('s_{0}'('s_{2}')) = s ⊃
    ¬(¬'s_{2}' < 's_{0}'('s_{2}') ∨ ¬f('s_{0}'('s_{2}')) = s)) ∧
(¬(¬'s_{6}' < 's_{4}'('s_{6}') ∨ ¬f('s_{4}'('s_{6}')) = s) ⊃
    's_{6}' < 's_{4}'('s_{6}') ∧ f('s_{4}'('s_{6}')) = s)
```

**Comment by quicquid** [comment]
Perfect! Thanks for the help!
