### ISSUE TITLE
'sbt releaseDist' fails with FileNotFoundException

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#508]
On running "sbt releaseDist" I get
```
Latexmk: This is Latexmk, John Collins, 11 Nov. 2012, version: 4.35.
**** Report bugs etc to John Collins <collins at phys.psu.edu>. ****
Latexmk: All targets (user_manual.pdf) are up-to-date
java.io.FileNotFoundException: /home/stefan/Uni/Software/gapt-devel/rep/gapt/target/scala-2.11/unidoc (Datei oder Verzeichnis nicht gefunden)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at sbt.Using$$anonfun$fileInputStream$1.apply(Using.scala:73)
        at sbt.Using$$anonfun$fileInputStream$1.apply(Using.scala:73)
        at sbt.Using$$anon$2.openImpl(Using.scala:65)
        at sbt.OpenFile$class.open(Using.scala:43)
        at sbt.Using$$anon$2.open(Using.scala:64)
        at sbt.Using$$anon$2.open(Using.scala:64)
        at sbt.Using.apply(Using.scala:23)
        at sbt.IO$.transfer(IO.scala:305)
        at $a5b81773ec87f23d2c71$$anonfun$root$14$$anonfun$apply$2$$anonfun$apply$3.apply(build.sbt:125)
        at $a5b81773ec87f23d2c71$$anonfun$root$14$$anonfun$apply$2$$anonfun$apply$3.apply(build.sbt:120)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at $a5b81773ec87f23d2c71$$anonfun$root$14$$anonfun$apply$2.apply(build.sbt:120)
        at $a5b81773ec87f23d2c71$$anonfun$root$14$$anonfun$apply$2.apply(build.sbt:116)
        at sbt.Using.apply(Using.scala:24)
        at sbt.IO$$anonfun$gzipFileOut$1$$anonfun$apply$6.apply(IO.scala:852)
        at sbt.IO$$anonfun$gzipFileOut$1$$anonfun$apply$6.apply(IO.scala:851)
        at sbt.Using.apply(Using.scala:24)
        at sbt.IO$$anonfun$gzipFileOut$1.apply(IO.scala:851)
        at sbt.IO$$anonfun$gzipFileOut$1.apply(IO.scala:850)
        at sbt.Using.apply(Using.scala:24)
        at sbt.IO$.gzipFileOut(IO.scala:850)
        at $a5b81773ec87f23d2c71$$anonfun$root$14.apply(build.sbt:116)
        at $a5b81773ec87f23d2c71$$anonfun$root$14.apply(build.sbt:93)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (root/*:releaseDist) java.io.FileNotFoundException: /home/stefan/Uni/Software/gapt-devel/rep/gapt/target/scala-2.11/unidoc (Datei oder Verzeichnis nicht gefunden)
[error] Total time: 191 s, completed 11.04.2016 13:36:55
```

The contents of my target/scala-2.11/ is:
```
stefan@clogic83:~/Uni/Software/gapt-devel/rep/gapt$ cd target/scala-2.11/
stefan@clogic83:~/Uni/Software/gapt-devel/rep/gapt/target/scala-2.11$ ls -l
insgesamt 69012
-rw-rw-r-- 1 stefan stefan 70667923 Apr 11 13:36 root-assembly-2.1-SNAPSHOT.jar
stefan@clogic83:~/Uni/Software/gapt-devel/rep/gapt/target/scala-2.11$ 
```

**Comment by gebner** [comment]
This happened because the releaseDist task didn't depend on the unidoc task, just on the key that defined the output path.

We didn't notice this on jenkins, because there we manually call unidoc first.
