### ISSUE TITLE
ViperTest failure

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#567]
On running "sbt test" I get the following failure in ViperTest.
```
[error]   ! comm
[error]    scala.MatchError: None (of class scala.None$) (Viper.scala:192)
[error] at.logic.gapt.provers.viper.Viper.solveSPWI(Viper.scala:192)
[error] at.logic.gapt.provers.viper.Viper.solve(Viper.scala:125)
[error] at.logic.gapt.provers.viper.ViperTest$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(ViperTest.scala:37)
[error] at.logic.gapt.provers.viper.ViperTest$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(ViperTest.scala:24)
```

**Comment by loewenheim** [comment]
I think that might be the same one I get on my work computer, but not on my computer at home.

**Comment by gebner** [comment]
The error does not happen here.  I believe the reason for that is that we choose the MaxSAT solver based on what is installed, i.e. first try OpenWBO, then qmaxsat, then MaxSAT4J.  On travis, we only have maxsat4j and it works.  On the compile server and my laptop, there is OpenWBO and it works as well.  It seems that this problem only occurs with qmaxsat.

Could please either of you run `sbt scripts` and then `..../gapt/target/viper .../gapt/examples/induction/comm.smt2`, and paste the output here?  It would be interesting to see the failure mode.  As a last resort, we can always disable the qmaxsat fallback, or disable the test if qmaxsat is installed.

**Comment by shetzl** [comment]
This seems indeed related to qmaxsat; after renaming the qmaxsat binary, the test passes.

Running `sbt scripts` and `../gapt/target/viper ../gapt/examples/induction/comm.smt2` yields the following output:
```
∀x0 (p(s(x0:nat): nat): nat) = x0,
∀x (plus(x:nat, o:nat): nat) = x,
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1)),
∀y0 ¬o = s(y0),
∀x plus(o, x) = x,
∀x ∀y plus(s(x), y) = s(plus(x, y))
⊢
∀x plus(x, k) = plus(k, x)
Proving instance List(s(o))
Instance proof for List(s(o)):
∀x plus(o, x) = x +^{k} (plus(o, k) = k)-,
∀x ∀y plus(s(x), y) = s(plus(x, y))
  +^{o}
    (∀y plus(s(o), y) = s(plus(o, y))
      +^{k} (plus(s(o), k) = s(plus(o, k)))-),
∀x plus(x, o) = x +^{k} (plus(k, o) = k)-,
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1))
  +^{k}
    (∀y1 plus(k, s(y1)) = s(plus(k, y1))
      +^{o} (plus(k, s(o)) = s(plus(k, o)))-)
:-
(plus(s(o), k) = plus(k, s(o)))+
Language:
'a1:plus(x,o)=x'(k:nat): _Inst
'a2:plus(x,s(y1))=s(plus(x,y1))'(k:nat, o:nat): _Inst
'a4:plus(o,x)=x'(k:nat): _Inst
'a5:plus(s(x),y)=s(plus(x,y))'(o:nat, k:nat): _Inst
's0:plus(x,k)=plus(k,x)':_Inst
Proving instance List(o)
Instance proof for List(o):
∀x plus(o, x) = x +^{k} (plus(o, k) = k)-,
∀x plus(x, o) = x +^{k} (plus(k, o) = k)-
:-
(plus(o, k) = plus(k, o))+
Language:
'a1:plus(x,o)=x'(k:nat): _Inst
'a4:plus(o,x)=x'(k:nat): _Inst
's0:plus(x,k)=plus(k,x)':_Inst
Found schematic proof with induction:
ProofByRecursionScheme(∀x0 (p(s(x0:nat): nat): nat) = x0,                                                                                                                                                                                    
∀x (plus(x:nat, o:nat): nat) = x,                                                                                                                                                                                                            
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1)),                                                                                                                                                                                                      
∀y0 ¬o = s(y0),                                                                                                                                                                                                                              
∀x plus(o, x) = x,                                                                                                                                                                                                                           
∀x ∀y plus(s(x), y) = s(plus(x, y))                                                                                                                                                                                                          
⊢                                                                                                                                                                                                                                            
∀x plus(x, k) = plus(k, x),Non-terminals: A:nat>o, B:nat>nat>nat>o                                                                                                                                                                           
Terminals: '=':nat>nat>o, k:nat, o:nat, plus:nat>nat>nat, s:nat>nat                                                                                                                                                                          
                                                                                                                                                                                                                                             
A(x0) → plus(k, o) = k                                                                                                                                                                                                                       
A(x0) → plus(k, s(o)) = s(plus(k, o))                                                                                                                                                                                                        
A(x0) → plus(o, k) = k                                                                                                                                                                                                                       
A(x0) → plus(s(o), k) = s(plus(o, k))                                                                                                                                                                                                        
B(x0, x1, x2) → plus(k, o) = k                                                                                                                                                                                                               
B(x0, x1, x2) → plus(k, s(o)) = s(plus(k, o))                                                                                                                                                                                                
B(x0, x1, x2) → plus(o, k) = k                                                                                                                                                                                                               
B(x0, x1, x2) → plus(s(o), k) = s(plus(o, k))                                                                                                                                                                                                
,InductiveType(o,Vector(⊤, ⊥))                                                                                                                                                                                                               
ConstDecl('¬')                                                                                                                                                                                                                               
ConstDecl('∧')                                                                                                                                                                                                                               
ConstDecl('∨')                                                                                                                                                                                                                               
ConstDecl('⊃')                                                                                                                                                                                                                               
ConstDecl('∀')                                                                                                                                                                                                                               
ConstDecl('∃')
ConstDecl('=')
InductiveType(nat,Vector(o:nat, s:nat>nat))
ConstDecl(p:nat>nat)
ConstDecl(plus:nat>nat>nat)
ConstDecl(k:nat))

Checking validity for instance List(o): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(o)))))))))): false
Minimal counterexample: List(s(s(o)))
Proving instance List(s(s(o)))
Instance proof for List(s(s(o))):
∀x plus(o, x) = x +^{k} (plus(o, k) = k)-,
∀x ∀y plus(s(x), y) = s(plus(x, y))
  +^{o}
    (∀y plus(s(o), y) = s(plus(o, y))
      +^{k} (plus(s(o), k) = s(plus(o, k)))-)
  +^{s(o)}
    (∀y plus(s(s(o)), y) = s(plus(s(o), y))
      +^{k} (plus(s(s(o)), k) = s(plus(s(o), k)))-),
∀x plus(x, o) = x +^{k} (plus(k, o) = k)-,
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1))
  +^{k}
    (∀y1 plus(k, s(y1)) = s(plus(k, y1))
      +^{o} (plus(k, s(o)) = s(plus(k, o)))-
      +^{s(o)} (plus(k, s(s(o))) = s(plus(k, s(o))))-)
:-
(plus(s(s(o)), k) = plus(k, s(s(o))))+
Language:
'a1:plus(x,o)=x'(k:nat): _Inst
'a2:plus(x,s(y1))=s(plus(x,y1))'(k:nat, o:nat): _Inst
'a2:plus(x,s(y1))=s(plus(x,y1))'(k:nat, s(o:nat): nat): _Inst
'a4:plus(o,x)=x'(k:nat): _Inst
'a5:plus(s(x),y)=s(plus(x,y))'(o:nat, k:nat): _Inst
'a5:plus(s(x),y)=s(plus(x,y))'(s(o:nat): nat, k:nat): _Inst
's0:plus(x,k)=plus(k,x)':_Inst
Found schematic proof with induction:
ProofByRecursionScheme(∀x0 (p(s(x0:nat): nat): nat) = x0,
∀x (plus(x:nat, o:nat): nat) = x,
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1)),
∀y0 ¬o = s(y0),
∀x plus(o, x) = x,
∀x ∀y plus(s(x), y) = s(plus(x, y))
⊢
∀x plus(x, k) = plus(k, x),Non-terminals: A:nat>o, B:nat>nat>nat>o
Terminals: '=':nat>nat>o, k:nat, o:nat, plus:nat>nat>nat, s:nat>nat

A(x0) → plus(k, o) = k
A(x0) → plus(k, s(o)) = s(plus(k, o))
A(x0) → plus(k, s(s(o))) = s(plus(k, s(o)))
A(x0) → plus(o, k) = k
A(x0) → plus(s(o), k) = s(plus(o, k))
A(x0) → plus(s(s(o)), k) = s(plus(s(o), k))
B(x0, x1, x2) → plus(k, o) = k
B(x0, x1, x2) → plus(k, s(o)) = s(plus(k, o))
B(x0, x1, x2) → plus(k, s(s(o))) = s(plus(k, s(o)))
B(x0, x1, x2) → plus(o, k) = k
B(x0, x1, x2) → plus(s(o), k) = s(plus(o, k))
B(x0, x1, x2) → plus(s(s(o)), k) = s(plus(s(o), k))
,InductiveType(o,Vector(⊤, ⊥))
ConstDecl('¬')
ConstDecl('∧')
ConstDecl('∨')
ConstDecl('⊃')
ConstDecl('∀')
ConstDecl('∃')
ConstDecl('=')
InductiveType(nat,Vector(o:nat, s:nat>nat))
ConstDecl(p:nat>nat)
ConstDecl(plus:nat>nat>nat)
ConstDecl(k:nat))

Checking validity for instance List(o): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(o)))))))))): false
Minimal counterexample: List(s(s(s(o))))
Proving instance List(s(s(s(o))))
Instance proof for List(s(s(s(o)))):
∀x plus(o, x) = x +^{k} (plus(o, k) = k)-,
∀x ∀y plus(s(x), y) = s(plus(x, y))
  +^{o}
    (∀y plus(s(o), y) = s(plus(o, y))
      +^{k} (plus(s(o), k) = s(plus(o, k)))-)
  +^{s(o)}
    (∀y plus(s(s(o)), y) = s(plus(s(o), y))
      +^{k} (plus(s(s(o)), k) = s(plus(s(o), k)))-)
  +^{s(s(o))}
    (∀y plus(s(s(s(o))), y) = s(plus(s(s(o)), y))
      +^{k} (plus(s(s(s(o))), k) = s(plus(s(s(o)), k)))-),
∀x plus(x, o) = x +^{k} (plus(k, o) = k)-,
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1))
  +^{k}
    (∀y1 plus(k, s(y1)) = s(plus(k, y1))
      +^{o} (plus(k, s(o)) = s(plus(k, o)))-
      +^{s(o)} (plus(k, s(s(o))) = s(plus(k, s(o))))-
      +^{s(s(o))} (plus(k, s(s(s(o)))) = s(plus(k, s(s(o)))))-)
:-
(plus(s(s(s(o))), k) = plus(k, s(s(s(o)))))+
Language:
'a1:plus(x,o)=x'(k:nat): _Inst
'a2:plus(x,s(y1))=s(plus(x,y1))'(k:nat, o:nat): _Inst
'a2:plus(x,s(y1))=s(plus(x,y1))'(k:nat, s(o:nat): nat): _Inst
'a2:plus(x,s(y1))=s(plus(x,y1))'(k:nat, s(s(o:nat): nat)): _Inst
'a4:plus(o,x)=x'(k:nat): _Inst
'a5:plus(s(x),y)=s(plus(x,y))'(o:nat, k:nat): _Inst
'a5:plus(s(x),y)=s(plus(x,y))'(s(o:nat): nat, k:nat): _Inst
'a5:plus(s(x),y)=s(plus(x,y))'(s(s(o:nat): nat), k:nat): _Inst
's0:plus(x,k)=plus(k,x)':_Inst
Found schematic proof with induction:
ProofByRecursionScheme(∀x0 (p(s(x0:nat): nat): nat) = x0,
∀x (plus(x:nat, o:nat): nat) = x,
∀x ∀y1 plus(x, s(y1)) = s(plus(x, y1)),
∀y0 ¬o = s(y0),
∀x plus(o, x) = x,
∀x ∀y plus(s(x), y) = s(plus(x, y))
⊢
∀x plus(x, k) = plus(k, x),Non-terminals: A:nat>o, B:nat>nat>nat>o
Terminals: '=':nat>nat>o, k:nat, o:nat, plus:nat>nat>nat, s:nat>nat

A(x0) → plus(k, o) = k
A(x0) → plus(o, k) = k
A(x0) → B(x0, x0, o)
B(x0, o, x2) → plus(k, o) = k
B(x0, o, x2) → plus(k, s(x2)) = s(plus(k, x2))
B(x0, o, x2) → plus(o, k) = k
B(x0, o, x2) → plus(s(x2), k) = s(plus(x2, k))
B(x0, s(x1_0), x2) → plus(k, o) = k
B(x0, s(x1_0), x2) → plus(k, s(x2)) = s(plus(k, x2))
B(x0, s(x1_0), x2) → plus(o, k) = k
B(x0, s(x1_0), x2) → plus(s(x2), k) = s(plus(x2, k))
B(x0, s(x1_0), x2) → B(x0, x1_0, s(x2))
,InductiveType(o,Vector(⊤, ⊥))
ConstDecl('¬')
ConstDecl('∧')
ConstDecl('∨')
ConstDecl('⊃')
ConstDecl('∀')
ConstDecl('∃')
ConstDecl('=')
InductiveType(nat,Vector(o:nat, s:nat>nat))
ConstDecl(p:nat>nat)
ConstDecl(plus:nat>nat>nat)
ConstDecl(k:nat))

Checking validity for instance List(o): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(o)))))))))): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(s(o))))))))))): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(s(s(o)))))))))))): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(s(s(s(o))))))))))))): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(s(s(s(s(o)))))))))))))): true
Checking validity for instance List(s(s(s(s(s(s(s(s(s(s(s(s(s(s(o))))))))))))))): true
Solution condition:
∃X_B (∀x_2 ∀x_0 (plus(o, k) = k ∧
          plus(k, s(x_2)) = s(plus(k, x_2)) ∧
          plus(k, o) = k ∧
          plus(s(x_2), k) = s(plus(x_2, k)) ⊃
        X_B(x_0:nat, o, x_2)) ∧
    ∀x_0 ∀x_2 ∀x_3 (plus(k, o) = k ∧
          X_B(x_0, x_2, s(x_3)) ∧
          plus(k, s(x_3)) = s(plus(k, x_3)) ∧
          plus(o, k) = k ∧
          plus(s(x_3), k) = s(plus(x_3, k)) ⊃
        X_B(x_0, s(x_2), x_3)) ∧
    ∀x (plus(o, k) = k ∧ X_B(x, x, o) ∧ plus(k, o) = k ⊃
        plus(x, k) = plus(k, x)))

Canonical solution at X_B(y_0:nat, s(o), w_0:nat): o:
 :- plus(s(s(w_0)), k) = s(plus(s(w_0), k))
 :- plus(k, s(w_0)) = s(plus(k, w_0))
 :- plus(o, k) = k
 :- plus(s(w_0), k) = s(plus(w_0, k))
 :- plus(k, s(s(w_0))) = s(plus(k, s(w_0)))
 :- plus(k, o) = k
Exception in thread "main" scala.MatchError: None (of class scala.None$)
        at at.logic.gapt.provers.viper.Viper.solveSPWI(Viper.scala:192)
        at at.logic.gapt.provers.viper.Viper.solve(Viper.scala:125)
        at at.logic.gapt.provers.viper.Viper$.main(Viper.scala:279)
        at at.logic.gapt.provers.viper.Viper.main(Viper.scala)
```

Between printing the `Canonical solution at X_B(y_0:nat, s(o), w_0:nat): o` and throwing the exception, a few minutes pass.

**Comment by gebner** [comment]
Thanks for posting the output!  Does the last commit fix the bug for you?

**Comment by shetzl** [comment]
Yes, this fixes the bug for me.
