### ISSUE TITLE
Tactic escargot throws exception

### ISSUE THREAD

**Issue by jannikvierling** [gapt/gapt#580]
The escargot tactic sometimes fails to prove valid sequents and throws an exception. This especially happens if the right hand side of the sequent contains formulas of the form ∀x P.

For example: 
```
import at.logic.gapt.proofs.gaptic.{ TacticsProof, _ }

object bugEscargotTactic extends TacticsProof {
  val proof = Lemma (("a" -> hof"!y P(y)") +: Sequent() :+ ("b" -> hof"!x P(x)")) {
    escargot
  }
}
```
Evaluating `bugEscargotTactic.proof` yields:

```
at.logic.gapt.proofs.gaptic.TacticFailureException: Exception when applying EscargotTactic to proof state with sub goals:
a: ∀y P(y)
:-
b: ∀x P(x)

  at at.logic.gapt.proofs.gaptic.LemmaMacros$.use(language.scala:25)
  ... 31 elided
Caused by: java.lang.IllegalArgumentException: requirement failed
  at scala.Predef$.require(Predef.scala:212)
  at at.logic.gapt.expr.hol.SkolemFunctions$$anonfun$1.apply(SkolemFunctions.scala:24)
  at at.logic.gapt.expr.hol.SkolemFunctions$$anonfun$1.apply(SkolemFunctions.scala:21)
  at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
  at at.logic.gapt.expr.hol.SkolemFunctions.<init>(SkolemFunctions.scala:21)
  at at.logic.gapt.expr.hol.SkolemFunctions$.apply(SkolemFunctions.scala:46)
  at at.logic.gapt.proofs.expansion.ExpansionProof.<init>(expansionProofs.scala:34)
  at at.logic.gapt.proofs.expansion.replaceET$.apply(expansionTrees.scala:377)
  at at.logic.gapt.proofs.expansion.package$expansionProofsAreReplaceable$.replace(package.scala:42)
  at at.logic.gapt.proofs.expansion.package$expansionProofsAreReplaceable$.replace(package.scala:41)
  at at.logic.gapt.expr.TermReplacement$.apply(TermReplacement.scala:136)
  at at.logic.gapt.expr.TermReplacement$.hygienic(TermReplacement.scala:152)
  at at.logic.gapt.provers.groundFreeVariables$$anonfun$wrap$2.apply(utils.scala:43)
  at scala.Option.map(Option.scala:146)
  at at.logic.gapt.provers.groundFreeVariables$.wrap(utils.scala:43)
  at at.logic.gapt.provers.ResolutionProver$class.getExpansionProof(ResolutionProver.scala:48)
  at at.logic.gapt.provers.escargot.Escargot.getExpansionProof(escargot.scala:96)
  at at.logic.gapt.proofs.gaptic.tactics.EscargotTactic$.apply(complexTactics.scala:315)
  at at.logic.gapt.proofs.gaptic.Tactic$class.apply(core.scala:249)
  at at.logic.gapt.proofs.gaptic.tactics.EscargotTactic$.apply(complexTactics.scala:313)
  at at.logic.gapt.proofs.gaptic.LemmaMacros$.use(language.scala:23)
  ... 31 more
````

**Comment by gebner** [comment]
The problem is that `P` is a free higher-order variable here.  If you just declare `P` as a constant first, it will work just fine.

When passing a formula to a resolution prover, we first ground all free variables.  So in this case here we apply the substitution `#v(P:i>o) -> #c(P:i>o)`.  The exception then happens when we undo this substitution in the final proof, i.e. apply the replacement `#c(P:i>o) -> #v(P:i>o)`.  This would generate a definition whose right side is not a closed term.

**Comment by jannikvierling** [comment]
Thanks!
