### ISSUE TITLE
TIP import: mutually recursive functions

### ISSUE THREAD

**Issue by jannikvierling** [gapt/gapt#583]
Running `TipSmtParser.fixupAndParse` on the file `propositional_AndCommutative.smt2` from the TIP-Library produces a `scala.MatchError`.

Example:
```
object Bug {
  def main(args: Array[String]): Unit = {
    TipSmtParser fixupAndParse "./../benchmarks/benchmarks/tip2015/propositional_AndCommutative.smt2".toFile
  }
}
```
Output:
```
Exception in thread "main" scala.MatchError: (define-funs-rec ((models ((x Form) (y list2)) list) (models2 ((q Form) (x list)) list) (models5 ((q Form) (x list) (y list)) list)) ((match x (case (& q r) (models2 r (models q y))) (case (Not z) (match z (case (& p2 q2) (append (models (Not p2) y) (models (& p2 (Not q2)) y))) (case (Not p3) (models p3 y)) (case (Var x2) (ite (not (or2 (models3 x2 y))) (cons (cons2 (Pair2 x2 false) (filter (lam x2) y)) nil) nil)))) (case (Var x4) (ite (not (or2 (models4 x4 y))) (cons (cons2 (Pair2 x4 true) (filter (lam2 x4) y)) nil) nil))) (match x (case nil nil) (case (cons y z) (models5 q z (models q y)))) (match y (case nil (models2 q x)) (case (cons z x2) (cons z (models5 q x x2)))))) (of class at.logic.gapt.formats.lisp.LList)
	at at.logic.gapt.formats.tip.TipSmtParser.parse(tipsmt.scala:30)
	at at.logic.gapt.formats.tip.TipSmtParser$$anonfun$parse$4.apply(tipsmt.scala:156)
	at at.logic.gapt.formats.tip.TipSmtParser$$anonfun$parse$4.apply(tipsmt.scala:156)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at at.logic.gapt.formats.tip.TipSmtParser$.parse(tipsmt.scala:156)
	at at.logic.gapt.formats.tip.TipSmtParser$.fixupAndParse(tipsmt.scala:161)
```

A similar behaviour occurs when running TipSmtParser.fixupAndParse on the following files:
```
benchmarks/tip2015/sort_BSortIsSort.smt2
benchmarks/tip2015/sort_NStoogeSortCount.smt2
benchmarks/tip2015/sort_BSortSorts.smt2
benchmarks/tip2015/sort_BSortPermutes.smt2
benchmarks/tip2015/propositional_Okay.smt2
benchmarks/tip2015/sort_BSortCount.smt2
benchmarks/tip2015/sort_NStoogeSortPermutes.smt2
benchmarks/tip2015/sort_NStoogeSortSorts.smt2
benchmarks/tip2015/propositional_AndImplication.smt2
benchmarks/tip2015/list_PairEvens.smt2
benchmarks/tip2015/list_PairOdds.smt2
benchmarks/tip2015/sort_NStoogeSortIsSort.smt2
benchmarks/tip2015/propositional_Sound.smt2
benchmarks/tip2015/list_Interleave.smt2
benchmarks/tip2015/sort_NStoogeSort2IsSort.smt2
benchmarks/tip2015/sort_NStoogeSort2Count.smt2
benchmarks/tip2015/sort_NStoogeSort2Sorts.smt2
benchmarks/tip2015/propositional_AndIdempotent.smt2
benchmarks/tip2015/sort_NStoogeSort2Permutes.smt2
benchmarks/grammars/simp_expr_unambig4.smt2
```

**Comment by jannikvierling** [comment]
Fixed in PR #705.
