### ISSUE TITLE
EProver.getExpansionProof throws exception

### ISSUE THREAD

**Issue by jannikvierling** [gapt/gapt#588]
Example:
```
object Example {
  def main( args: Array[String] ): Unit = {
    EProver.getExpansionProof(fof"A" +: Sequent() :+ fof"A")
  }
}
```
The output is something like: 
```
Exception in thread "main" java.io.IOException: eproof --tptp3-format /tmp/gapt-6182705502294466547.tmp exited with value 127:
# Cannot determine problem status within resource limit

	at at.logic.gapt.utils.runProcess$.apply(runProcess.scala:21)
	at at.logic.gapt.utils.runProcess$$anonfun$withTempInputFile$1.apply(runProcess.scala:15)
	at at.logic.gapt.utils.runProcess$$anonfun$withTempInputFile$1.apply(runProcess.scala:14)
	at at.logic.gapt.utils.withTempFile$$anonfun$fromString$1.apply(tempFiles.scala:14)
	at at.logic.gapt.utils.withTempFile$$anonfun$fromString$1.apply(tempFiles.scala:12)
	at at.logic.gapt.utils.withTempFile$.apply(tempFiles.scala:8)
	at at.logic.gapt.utils.withTempFile$.fromString(tempFiles.scala:12)
	at at.logic.gapt.utils.runProcess$.withTempInputFile(runProcess.scala:14)
	at at.logic.gapt.provers.eprover.EProver$$anonfun$getResolutionProof$1.apply(eprover.scala:21)
	at at.logic.gapt.provers.eprover.EProver$$anonfun$getResolutionProof$1.apply(eprover.scala:18)
	at at.logic.gapt.provers.renameConstantsToFi$.wrap(utils.scala:20)
	at at.logic.gapt.provers.eprover.EProver.getResolutionProof(eprover.scala:17)
	at at.logic.gapt.provers.ResolutionProver$class.getResolutionProof(ResolutionProver.scala:27)
	at at.logic.gapt.provers.eprover.EProver.getResolutionProof(eprover.scala:15)
	at at.logic.gapt.provers.ResolutionProver$class.getResolutionProof(ResolutionProver.scala:42)
	at at.logic.gapt.provers.eprover.EProver.getResolutionProof(eprover.scala:15)
	at at.logic.gapt.provers.ResolutionProver$$anonfun$getExpansionProof$1.apply(ResolutionProver.scala:49)
	at at.logic.gapt.provers.ResolutionProver$$anonfun$getExpansionProof$1.apply(ResolutionProver.scala:48)
	at at.logic.gapt.provers.groundFreeVariables$.wrap(utils.scala:43)
	at at.logic.gapt.provers.ResolutionProver$class.getExpansionProof(ResolutionProver.scala:48)
	at at.logic.gapt.provers.eprover.EProver.getExpansionProof(eprover.scala:15)
```

**Comment by gebner** [comment]
This works here:
```
scala> EProver.getExpansionProof(fof"A" +: Sequent() :+ fof"A")
res4: Option[at.logic.gapt.proofs.expansion.ExpansionProof] = Some(A- :- A+)
```
What eprover version are you using?

(BTW, you can also use `fos"A :- A"` instead of `fof"A" +: Sequent() :+ fof"A"`.)

**Comment by jannikvierling** [comment]
I'm using version E 1.9.1-001 Sungma.

**Comment by jannikvierling** [comment]
It works with E 1.8-001 Gopaldhara
