### ISSUE TITLE
LKToExpansionProof fails during merge with invalid substitution

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#642]
Doing
```
val problem = TipSmtParser.fixupAndParse( "testing/TIP/benchmarks/isaplanner/prop_27.smt2" )
val Some( p ) = Viper( problem )
val q = makeInductionExplicit( p )
LKToExpansionProof( q )
```
in the CLI results in
```
java.lang.UnsupportedOperationException
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.applySubstitution(expansionTrees.scala:418)
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.applySubstitution(expansionTrees.scala:393)
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.applySubstitution(expansionTrees.scala:406)
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.applySubstitution(expansionTrees.scala:406)
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.$anonfun$applySubstitution$2(expansionTrees.scala:412)
  at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
  at scala.collection.Iterator.foreach(Iterator.scala:929)
  at scala.collection.Iterator.foreach$(Iterator.scala:929)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
  at scala.collection.IterableLike.foreach(IterableLike.scala:71)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.applySubstitution(expansionTrees.scala:411)
  at at.logic.gapt.proofs.expansion.expansionTreeSubstitution$.applySubstitution(expansionTrees.scala:391)
  at at.logic.gapt.expr.Substitution.apply(substitution.scala:83)
  at at.logic.gapt.proofs.expansion.eliminateMerges$.$anonfun$elim$4(eliminateMerges.scala:87)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  at scala.collection.Iterator.foreach(Iterator.scala:929)
  at scala.collection.Iterator.foreach$(Iterator.scala:929)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
  at scala.collection.IterableLike.foreach(IterableLike.scala:71)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike.map(TraversableLike.scala:234)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at at.logic.gapt.proofs.Sequent.map(sequents.scala:249)
  at at.logic.gapt.proofs.Sequent.map(sequents.scala:234)
  at at.logic.gapt.proofs.expansion.eliminateMerges$.elim(eliminateMerges.scala:87)
  at at.logic.gapt.proofs.expansion.eliminateMerges$.apply(eliminateMerges.scala:7)
  at at.logic.gapt.proofs.lk.LKToExpansionProof$.apply(LKToExpansionProof.scala:20)
  ... 26 elided
```
Analogous behaviour is exhibited by `prod/prop_37.smt2` and `prod/prop_38.smt2`.

**Comment by gebner** [comment]
I think this happens when merging Skolem nodes and strong quantifier nodes, but I guess this is a case for better error messages.
