### ISSUE TITLE
Problem with SPASS when running for gapt cli

### ISSUE THREAD

**Issue by Ermine516** [gapt/gapt#667]
Currently on branch SchProofUpdate the following code.
---------------------------------------------------------------------------------------------------------------------------------
import at.logic.gapt.examples.NiaSchema
import NiaSchema.ctx
import at.logic.gapt.proofs.gaptic.tactics._
import at.logic.gapt.proofs.gaptic._
import at.logic.gapt.provers._
class proofes(initialContext: ImmutableContext ) extends TacticsProof(initialContext)  {
  def prove1(SCS:Map[Struct[Nothing], ( Struct[Nothing], Set[Var] )]):LKProof ={
    val es = Sequent(Seq("Ant_0" -> hof"omegaPR(s(0))"), Seq())
    Lemma(es) {
      unfold("omegaPR") atMost 1 in "Ant_0"
      unfold("chiPR") atMost 10 in "Ant_0"
      unfold("phiPR") atMost 10 in "Ant_0"
      unfold("chiPR") atMost 10 in "Ant_0"
      EscargotTactic()
    }
  }
}
val SCS = SchematicStruct( "omega" )( ctx ).getOrElse( Map() )
val ctx2 = ctx.newMutable
CharFormPRN.PR(CharFormPRN(SCS))(ctx2)
val proof = new proofes(ctx2.toImmutable).prove1(SCS)
val form = proof.subProofAt(List(0,0,0,0)).endSequent
SPASS.getLKProof(form)
---------------------------------------------------------------------------------------------------------------------------------

Results in the following error

---------------------------------------------------------------------------------------------------------------------------------
java.lang.ClassCastException: at.logic.gapt.expr.determineTraits$App_with_Atom cannot be cast to at.logic.gapt.expr.FOLAtom
  at at.logic.gapt.expr.Substitutable$.$anonfun$SubstitutableSequent$2(Substitutable.scala:122)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  at scala.collection.Iterator.foreach(Iterator.scala:929)
  at scala.collection.Iterator.foreach$(Iterator.scala:929)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
  at scala.collection.IterableLike.foreach(IterableLike.scala:71)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike.map(TraversableLike.scala:234)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at at.logic.gapt.proofs.Sequent.map(sequents.scala:249)
  at at.logic.gapt.proofs.Sequent.map(sequents.scala:234)
  at at.logic.gapt.expr.Substitutable$.$anonfun$SubstitutableSequent$1(Substitutable.scala:122)
  at at.logic.gapt.expr.FOLSubstitution.apply(substitution.scala:127)
  at at.logic.gapt.provers.spass.SPASS.cls2dfg(SPASS.scala:35)
  at at.logic.gapt.provers.spass.SPASS.$anonfun$getResolutionProof$2(SPASS.scala:46)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  at scala.collection.Iterator.foreach(Iterator.scala:929)
  at scala.collection.Iterator.foreach$(Iterator.scala:929)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
  at scala.collection.IterableLike.foreach(IterableLike.scala:71)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike.map(TraversableLike.scala:234)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at at.logic.gapt.provers.spass.SPASS.$anonfun$getResolutionProof$1(SPASS.scala:46)
  at at.logic.gapt.provers.renameConstantsToFi$.wrap(utils.scala:46)
  at at.logic.gapt.provers.spass.SPASS.getResolutionProof(SPASS.scala:39)
  at at.logic.gapt.provers.ResolutionProver.getResolutionProof(ResolutionProver.scala:31)
  at at.logic.gapt.provers.ResolutionProver.getResolutionProof$(ResolutionProver.scala:29)
  at at.logic.gapt.provers.spass.SPASS.getResolutionProof(SPASS.scala:18)
  at at.logic.gapt.provers.ResolutionProver.getResolutionProof(ResolutionProver.scala:55)
  at at.logic.gapt.provers.ResolutionProver.getResolutionProof$(ResolutionProver.scala:48)
  at at.logic.gapt.provers.spass.SPASS.getResolutionProof(SPASS.scala:18)
  at at.logic.gapt.provers.ResolutionProver.$anonfun$getLKProof$2(ResolutionProver.scala:18)
  at at.logic.gapt.proofs.withSection$.apply(section.scala:40)
  at at.logic.gapt.provers.ResolutionProver.getLKProof(ResolutionProver.scala:16)
  at at.logic.gapt.provers.ResolutionProver.getLKProof$(ResolutionProver.scala:14)
  at at.logic.gapt.provers.spass.SPASS.getLKProof(SPASS.scala:18)
  at at.logic.gapt.provers.ResolutionProver.getLKProof(ResolutionProver.scala:12)
  at at.logic.gapt.provers.ResolutionProver.getLKProof$(ResolutionProver.scala:12)
  at at.logic.gapt.provers.spass.SPASS.getLKProof(SPASS.scala:18)
  ... 25 elided

**Comment by shetzl** [comment]
Is it possible to reproduce this in the master branch?

**Comment by Ermine516** [comment]
I will try too. I haven't attempted this yet.

**Comment by Ermine516** [comment]
The following code results in the same error on master:

import at.logic.gapt.examples.NiaSchema
import NiaSchema.ctx
import at.logic.gapt.provers._
val proof = instantiateProof( le"omega (s 0)" )
val st = StructCreators.extract(proof)
val cs = CharacteristicClauseSet(st)
SPASS.getResolutionProof(cs)

**Comment by shetzl** [comment]
Thanks!

**Comment by gebner** [comment]
```scala
SPASS.extendToManySortedViaPredicates,getResolutionProof(cs)
```

**Comment by gebner** [comment]
As requested, this now also works in tactics:
```scala
Lemma(...) {
  resolutionProver(SPASS.extendToManySortedViaPredicates)
  resolutionProver(SPASS.extendToManySortedViaPredicates).withDeskolemization
}
```
